# These settings are synced to GitHub by https://probot.github.io/apps/settings/
# pliancy/.github:.github/settings.yaml

repository:
  # See https://developer.github.com/v3/repos/#edit for all available settings.

  # The name of the repository. Changing this will rename the repository
  name: asana-sdk

  # A short description of the repository that will show up on GitHub
  description: Wrapper around Asana&#39;s node SDK

  # A URL with more information about the repository
  homepage: https://github.com/pliancy/asana-sdk

  # A comma-separated list of topics to set on the repository
  topics:
