/* tslint:disable */
/* eslint-disable */
/**
 * Asana
 * This is the interface for interacting with the [Asana Platform](https://developers.asana.com). Our API reference is generated from our [OpenAPI spec] (https://raw.githubusercontent.com/Asana/openapi/master/defs/asana_oas.yaml).
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { AccessRequestTargetIdCompact } from './access-request-target-id-compact';
import { UserCompact } from './user-compact';

/**
 * A *access request* object represents a request to access a shareable resource within Asana. It includes the requester\'s information, approval status, and target resource details.
 * @export
 * @interface AccessRequestResponse
 */
export interface AccessRequestResponse {
    /**
     * Globally unique identifier of the resource, as a string.
     * @type {string}
     * @memberof AccessRequestResponse
     */
    'gid'?: string;
    /**
     * The base type of this resource.
     * @type {string}
     * @memberof AccessRequestResponse
     */
    'resource_type'?: string;
    /**
     * The message included in the access request, if any.
     * @type {string}
     * @memberof AccessRequestResponse
     */
    'message'?: string;
    /**
     * The current approval status of the request.
     * @type {string}
     * @memberof AccessRequestResponse
     */
    'approval_status'?: AccessRequestResponseApprovalStatusEnum;
    /**
     * 
     * @type {UserCompact}
     * @memberof AccessRequestResponse
     */
    'requester'?: UserCompact;
    /**
     * 
     * @type {AccessRequestTargetIdCompact}
     * @memberof AccessRequestResponse
     */
    'target'?: AccessRequestTargetIdCompact;
}

/**
    * @export
    * @enum {string}
    */
export enum AccessRequestResponseApprovalStatusEnum {
    Pending = 'pending',
    Approved = 'approved',
    Denied = 'denied'
}


