/* tslint:disable */
/* eslint-disable */
/**
 * Asana
 * This is the interface for interacting with the [Asana Platform](https://developers.asana.com). Our API reference is generated from our [OpenAPI spec] (https://raw.githubusercontent.com/Asana/developer-docs/master/defs/asana_oas.yaml).
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * The context from which this event originated.
 * @export
 * @interface AuditLogEventContext
 */
export interface AuditLogEventContext {
    /**
     * The type of context. Can be one of `web`, `desktop`, `mobile`, `asana_support`, `asana`, `email`, or `api`.
     * @type {string}
     * @memberof AuditLogEventContext
     */
    'context_type'?: AuditLogEventContextContextTypeEnum;
    /**
     * The authentication method used in the context of an API request. Only present if the `context_type` is `api`. Can be one of `cookie`, `oauth`, `personal_access_token`, or `service_account`.
     * @type {string}
     * @memberof AuditLogEventContext
     */
    'api_authentication_method'?: AuditLogEventContextApiAuthenticationMethodEnum;
    /**
     * The IP address of the client that initiated the event, if applicable.
     * @type {string}
     * @memberof AuditLogEventContext
     */
    'client_ip_address'?: string;
    /**
     * The user agent of the client that initiated the event, if applicable.
     * @type {string}
     * @memberof AuditLogEventContext
     */
    'user_agent'?: string;
    /**
     * The name of the OAuth App that initiated the event. Only present if the `api_authentication_method` is `oauth`.
     * @type {string}
     * @memberof AuditLogEventContext
     */
    'oauth_app_name'?: string;
}

/**
    * @export
    * @enum {string}
    */
export enum AuditLogEventContextContextTypeEnum {
    Web = 'web',
    Desktop = 'desktop',
    Mobile = 'mobile',
    AsanaSupport = 'asana_support',
    Asana = 'asana',
    Email = 'email',
    Api = 'api'
}
/**
    * @export
    * @enum {string}
    */
export enum AuditLogEventContextApiAuthenticationMethodEnum {
    Cookie = 'cookie',
    Oauth = 'oauth',
    PersonalAccessToken = 'personal_access_token',
    ServiceAccount = 'service_account'
}


