/* tslint:disable */
/* eslint-disable */
/**
 * Asana
 * This is the interface for interacting with the [Asana Platform](https://developers.asana.com). Our API reference is generated from our [OpenAPI spec] (https://raw.githubusercontent.com/Asana/openapi/master/defs/asana_oas.yaml).
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * A response object returned from a batch request.
 * @export
 * @interface BatchResponse
 */
export interface BatchResponse {
    /**
     * The HTTP status code that the invoked endpoint returned.
     * @type {number}
     * @memberof BatchResponse
     */
    'status_code'?: number;
    /**
     * A map of HTTP headers specific to this result. This is primarily used for returning a `Location` header to accompany a `201 Created` result.  The parent HTTP response will contain all common headers.
     * @type {object}
     * @memberof BatchResponse
     */
    'headers'?: object;
    /**
     * The JSON body that the invoked endpoint returned.
     * @type {object}
     * @memberof BatchResponse
     */
    'body'?: object;
}

