/* tslint:disable */
/* eslint-disable */
/**
 * Asana
 * This is the interface for interacting with the [Asana Platform](https://developers.asana.com). Our API reference is generated from our [OpenAPI spec] (https://raw.githubusercontent.com/Asana/openapi/master/defs/asana_oas.yaml).
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Defines the configuration of the actual portion of a budget. The actual value represents aggregated time tracking data attributed to the budget’s parent. This object controls which time entries are included based on their billable status. When no entries match the selected filter, the value will be 0.
 * @export
 * @interface BudgetActualRequest
 */
export interface BudgetActualRequest {
    /**
     * Billable status filter applied to time tracking entries contributing to the actual value. Determines which entries are included in aggregation. When not provided, defaults to `billable`.
     * @type {string}
     * @memberof BudgetActualRequest
     */
    'billable_status_filter'?: BudgetActualRequestBillableStatusFilterEnum;
}

/**
    * @export
    * @enum {string}
    */
export enum BudgetActualRequestBillableStatusFilterEnum {
    Billable = 'billable',
    NonBillable = 'non_billable',
    Any = 'any'
}


