/* tslint:disable */
/* eslint-disable */
/**
 * Asana
 * This is the interface for interacting with the [Asana Platform](https://developers.asana.com). Our API reference is generated from our [OpenAPI spec] (https://raw.githubusercontent.com/Asana/openapi/master/defs/asana_oas.yaml).
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { BudgetActualRequest } from './budget-actual-request';
import { BudgetCompact } from './budget-compact';
import { BudgetEstimateRequest } from './budget-estimate-request';
import { BudgetRequestAllOf } from './budget-request-all-of';
import { BudgetTotalRequest } from './budget-total-request';

/**
 * @type BudgetRequest
 * @export
 */
export type BudgetRequest = BudgetCompact & BudgetRequestAllOf;


