/* tslint:disable */
/* eslint-disable */
/**
 * Asana
 * This is the interface for interacting with the [Asana Platform](https://developers.asana.com). Our API reference is generated from our [OpenAPI spec] (https://raw.githubusercontent.com/Asana/openapi/master/defs/asana_oas.yaml).
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * A request to create a timesheet approval status.
 * @export
 * @interface CreateTimesheetApprovalStatusRequest
 */
export interface CreateTimesheetApprovalStatusRequest {
    /**
     * Globally unique identifier for the user whose timesheet this is.
     * @type {string}
     * @memberof CreateTimesheetApprovalStatusRequest
     */
    'user': string;
    /**
     * Globally unique identifier for the workspace.
     * @type {string}
     * @memberof CreateTimesheetApprovalStatusRequest
     */
    'workspace': string;
    /**
     * The start date of the timesheet week (must be a Monday).
     * @type {string}
     * @memberof CreateTimesheetApprovalStatusRequest
     */
    'start_date': string;
    /**
     * The end date of the timesheet week (must be the following Sunday).
     * @type {string}
     * @memberof CreateTimesheetApprovalStatusRequest
     */
    'end_date': string;
}

