/* tslint:disable */
/* eslint-disable */
/**
 * Asana
 * This is the interface for interacting with the [Asana Platform](https://developers.asana.com). Our API reference is generated from our [OpenAPI spec] (https://raw.githubusercontent.com/Asana/openapi/master/defs/asana_oas.yaml).
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface CreateTimeTrackingEntryRequest
 */
export interface CreateTimeTrackingEntryRequest {
    /**
     * Time in minutes tracked by the entry. Must be greater than 0
     * @type {number}
     * @memberof CreateTimeTrackingEntryRequest
     */
    'duration_minutes'?: number;
    /**
     * *Optional*. The day that this entry is logged on. Defaults to today if not specified
     * @type {string}
     * @memberof CreateTimeTrackingEntryRequest
     */
    'entered_on'?: string;
    /**
     * *Optional*. The gid of the project which the time is attributable to.
     * @type {string}
     * @memberof CreateTimeTrackingEntryRequest
     */
    'attributable_to'?: string;
    /**
     * *Optional*. The current billable status of the entry.
     * @type {string}
     * @memberof CreateTimeTrackingEntryRequest
     */
    'billable_status'?: CreateTimeTrackingEntryRequestBillableStatusEnum;
    /**
     * *Optional*. The description of the entry.
     * @type {string}
     * @memberof CreateTimeTrackingEntryRequest
     */
    'description'?: string;
    /**
     * *Optional*. The gids of time tracking categories to assign to this time tracking entry. Existing categories will be overridden. Currently limited to a maximum of 1 category.
     * @type {Array<string>}
     * @memberof CreateTimeTrackingEntryRequest
     */
    'categories'?: Array<string>;
}

/**
    * @export
    * @enum {string}
    */
export enum CreateTimeTrackingEntryRequestBillableStatusEnum {
    Billable = 'billable',
    NonBillable = 'nonBillable',
    NotApplicable = 'notApplicable'
}


