/* tslint:disable */
/* eslint-disable */
/**
 * Asana
 * This is the interface for interacting with the [Asana Platform](https://developers.asana.com). Our API reference is generated from our [OpenAPI spec] (https://raw.githubusercontent.com/Asana/developer-docs/master/defs/asana_oas.yaml).
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { CustomFieldResponse } from './custom-field-response';
import { ProjectCompact } from './project-compact';

/**
 * 
 * @export
 * @interface CustomFieldSettingResponseAllOf
 */
export interface CustomFieldSettingResponseAllOf {
    /**
     * 
     * @type {ProjectCompact & object}
     * @memberof CustomFieldSettingResponseAllOf
     */
    'project'?: ProjectCompact & object;
    /**
     * `is_important` is used in the Asana web application to determine if this custom field is displayed in the list/grid view of a project or portfolio.
     * @type {boolean}
     * @memberof CustomFieldSettingResponseAllOf
     */
    'is_important'?: boolean;
    /**
     * 
     * @type {ProjectCompact & object}
     * @memberof CustomFieldSettingResponseAllOf
     */
    'parent'?: ProjectCompact & object;
    /**
     * 
     * @type {CustomFieldResponse & object}
     * @memberof CustomFieldSettingResponseAllOf
     */
    'custom_field'?: CustomFieldResponse & object;
}

