/* tslint:disable */
/* eslint-disable */
/**
 * Asana
 * This is the interface for interacting with the [Asana Platform](https://developers.asana.com). Our API reference is generated from our [OpenAPI spec] (https://raw.githubusercontent.com/Asana/developer-docs/master/defs/asana_oas.yaml).
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { EnumOption } from './enum-option';

/**
 * 
 * @export
 * @interface CustomFieldBaseAllOf
 */
export interface CustomFieldBaseAllOf {
    /**
     * [Opt In](/docs/input-output-options). The description of the custom field.
     * @type {string}
     * @memberof CustomFieldBaseAllOf
     */
    'description'?: string;
    /**
     * *Conditional*. Only relevant for custom fields of type `enum`. This array specifies the possible values which an `enum` custom field can adopt. To modify the enum options, refer to [working with enum options](/docs/create-an-enum-option).
     * @type {Array<EnumOption>}
     * @memberof CustomFieldBaseAllOf
     */
    'enum_options'?: Array<EnumOption>;
    /**
     * Only relevant for custom fields of type ‘Number’. This field dictates the number of places after the decimal to round to, i.e. 0 is integer values, 1 rounds to the nearest tenth, and so on. Must be between 0 and 6, inclusive. For percentage format, this may be unintuitive, as a value of 0.25 has a precision of 0, while a value of 0.251 has a precision of 1. This is due to 0.25 being displayed as 25%. The identifier format will always have a precision of 0.
     * @type {number}
     * @memberof CustomFieldBaseAllOf
     */
    'precision'?: number;
    /**
     * The format of this custom field.
     * @type {string}
     * @memberof CustomFieldBaseAllOf
     */
    'format'?: CustomFieldBaseAllOfFormatEnum;
    /**
     * ISO 4217 currency code to format this custom field. This will be null if the `format` is not `currency`.
     * @type {string}
     * @memberof CustomFieldBaseAllOf
     */
    'currency_code'?: string | null;
    /**
     * This is the string that appears next to the custom field value. This will be null if the `format` is not `custom`.
     * @type {string}
     * @memberof CustomFieldBaseAllOf
     */
    'custom_label'?: string | null;
    /**
     * Only relevant for custom fields with `custom` format. This depicts where to place the custom label. This will be null if the `format` is not `custom`.
     * @type {string}
     * @memberof CustomFieldBaseAllOf
     */
    'custom_label_position'?: CustomFieldBaseAllOfCustomLabelPositionEnum;
    /**
     * This flag describes whether this custom field is available to every container in the workspace. Before project-specific custom fields, this field was always true.
     * @type {boolean}
     * @memberof CustomFieldBaseAllOf
     */
    'is_global_to_workspace'?: boolean;
    /**
     * *Conditional*. This flag describes whether a follower of a task with this field should receive inbox notifications from changes to this field.
     * @type {boolean}
     * @memberof CustomFieldBaseAllOf
     */
    'has_notifications_enabled'?: boolean;
}

/**
    * @export
    * @enum {string}
    */
export enum CustomFieldBaseAllOfFormatEnum {
    Currency = 'currency',
    Identifier = 'identifier',
    Percentage = 'percentage',
    Custom = 'custom',
    None = 'none'
}
/**
    * @export
    * @enum {string}
    */
export enum CustomFieldBaseAllOfCustomLabelPositionEnum {
    Prefix = 'prefix',
    Suffix = 'suffix'
}


