/* tslint:disable */
/* eslint-disable */
/**
 * Asana
 * This is the interface for interacting with the [Asana Platform](https://developers.asana.com). Our API reference is generated from our [OpenAPI spec] (https://raw.githubusercontent.com/Asana/openapi/master/defs/asana_oas.yaml).
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { UserCompact } from './user-compact';

/**
 * 
 * @export
 * @interface CustomFieldResponseAllOf
 */
export interface CustomFieldResponseAllOf {
    /**
     * This field tells the type of the custom field.
     * @type {string}
     * @memberof CustomFieldResponseAllOf
     */
    'representation_type'?: CustomFieldResponseAllOfRepresentationTypeEnum;
    /**
     * This field is the unique custom ID string for the custom field.
     * @type {string}
     * @memberof CustomFieldResponseAllOf
     */
    'id_prefix'?: string | null;
    /**
     * *Conditional*. This flag describes whether a custom field is a formula custom field.
     * @type {boolean}
     * @memberof CustomFieldResponseAllOf
     */
    'is_formula_field'?: boolean;
    /**
     * *Conditional*. This flag describes whether a custom field is read only.
     * @type {boolean}
     * @memberof CustomFieldResponseAllOf
     */
    'is_value_read_only'?: boolean;
    /**
     * 
     * @type {UserCompact}
     * @memberof CustomFieldResponseAllOf
     */
    'created_by'?: UserCompact;
    /**
     * *Conditional*. Only relevant for custom fields of type `people`. This array of [compact user](/reference/users) objects reflects the values of a `people` custom field.
     * @type {Array<UserCompact>}
     * @memberof CustomFieldResponseAllOf
     */
    'people_value'?: Array<UserCompact>;
}

/**
    * @export
    * @enum {string}
    */
export enum CustomFieldResponseAllOfRepresentationTypeEnum {
    Text = 'text',
    Enum = 'enum',
    MultiEnum = 'multi_enum',
    Number = 'number',
    Date = 'date',
    People = 'people',
    Formula = 'formula',
    CustomId = 'custom_id'
}


