/* tslint:disable */
/* eslint-disable */
/**
 * Asana
 * This is the interface for interacting with the [Asana Platform](https://developers.asana.com). Our API reference is generated from our [OpenAPI spec] (https://raw.githubusercontent.com/Asana/developer-docs/master/defs/asana_oas.yaml).
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { EnumOption } from './enum-option';
import { UserCompact } from './user-compact';

/**
 * 
 * @export
 * @interface CustomFieldResponseAllOf
 */
export interface CustomFieldResponseAllOf {
    /**
     * 
     * @type {EnumOption & object}
     * @memberof CustomFieldResponseAllOf
     */
    'enum_value'?: EnumOption & object;
    /**
     * *Conditional*. Only relevant for custom fields of type `multi_enum`. This object is the chosen values of a multi_enum custom field.
     * @type {Array<EnumOption>}
     * @memberof CustomFieldResponseAllOf
     */
    'multi_enum_values'?: Array<EnumOption>;
    /**
     * 
     * @type {UserCompact}
     * @memberof CustomFieldResponseAllOf
     */
    'created_by'?: UserCompact;
}

