/* tslint:disable */
/* eslint-disable */
/**
 * Asana
 * This is the interface for interacting with the [Asana Platform](https://developers.asana.com). Our API reference is generated from our [OpenAPI spec] (https://raw.githubusercontent.com/Asana/openapi/master/defs/asana_oas.yaml).
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { AsanaNamedResource } from './asana-named-resource';
import { UserCompact } from './user-compact';

/**
 * 
 * @export
 * @interface CustomFieldResponseAllOf
 */
export interface CustomFieldResponseAllOf {
    /**
     * This field tells the type of the custom field.
     * @type {string}
     * @memberof CustomFieldResponseAllOf
     */
    'representation_type'?: CustomFieldResponseAllOfRepresentationTypeEnum;
    /**
     * This field is the unique custom ID string for the custom field.
     * @type {string}
     * @memberof CustomFieldResponseAllOf
     */
    'id_prefix'?: string | null;
    /**
     * 
     * @type {Array<string>}
     * @memberof CustomFieldResponseAllOf
     */
    'input_restrictions'?: Array<CustomFieldResponseAllOfInputRestrictionsEnum>;
    /**
     * *Conditional*. This flag describes whether a custom field is a formula custom field.
     * @type {boolean}
     * @memberof CustomFieldResponseAllOf
     */
    'is_formula_field'?: boolean;
    /**
     * *Conditional*. This flag describes whether a custom field is read only.
     * @type {boolean}
     * @memberof CustomFieldResponseAllOf
     */
    'is_value_read_only'?: boolean;
    /**
     * 
     * @type {UserCompact}
     * @memberof CustomFieldResponseAllOf
     */
    'created_by'?: UserCompact;
    /**
     * *Conditional*. Only relevant for custom fields of type `people`. This array of [compact user](/reference/users) objects reflects the values of a `people` custom field.
     * @type {Array<UserCompact>}
     * @memberof CustomFieldResponseAllOf
     */
    'people_value'?: Array<UserCompact>;
    /**
     * *Conditional*. Only relevant for custom fields of type `reference`. This array of objects reflects the values of a `reference` custom field.
     * @type {Array<AsanaNamedResource>}
     * @memberof CustomFieldResponseAllOf
     */
    'reference_value'?: Array<AsanaNamedResource>;
    /**
     * *Conditional*. Only relevant for custom fields of type `text`. This is the HTML representation of the text value of a custom field, corresponding to the `text_value` plain-text field.
     * @type {string}
     * @memberof CustomFieldResponseAllOf
     */
    'html_text_value'?: string | null;
    /**
     * The privacy setting of the custom field. *Note: Administrators in your organization may restrict the values of `privacy_setting`.*
     * @type {string}
     * @memberof CustomFieldResponseAllOf
     */
    'privacy_setting'?: CustomFieldResponseAllOfPrivacySettingEnum;
    /**
     * The default access level when inviting new members to the custom field. This isn\'t applied when the `privacy_setting` is `private`, or the user is a guest. For local fields in a project or portfolio, the user must additionally have permission to modify the container itself.
     * @type {string}
     * @memberof CustomFieldResponseAllOf
     */
    'default_access_level'?: CustomFieldResponseAllOfDefaultAccessLevelEnum;
    /**
     * The type of the custom field. Must be one of the given values. 
     * @type {string}
     * @memberof CustomFieldResponseAllOf
     */
    'resource_subtype'?: CustomFieldResponseAllOfResourceSubtypeEnum;
}

/**
    * @export
    * @enum {string}
    */
export enum CustomFieldResponseAllOfRepresentationTypeEnum {
    Text = 'text',
    Enum = 'enum',
    MultiEnum = 'multi_enum',
    Number = 'number',
    Date = 'date',
    People = 'people',
    Formula = 'formula',
    CustomId = 'custom_id',
    Reference = 'reference'
}
/**
    * @export
    * @enum {string}
    */
export enum CustomFieldResponseAllOfInputRestrictionsEnum {
    Task = 'task',
    Project = 'project',
    Portfolio = 'portfolio',
    Goal = 'goal'
}
/**
    * @export
    * @enum {string}
    */
export enum CustomFieldResponseAllOfPrivacySettingEnum {
    PublicWithGuests = 'public_with_guests',
    Public = 'public',
    Private = 'private'
}
/**
    * @export
    * @enum {string}
    */
export enum CustomFieldResponseAllOfDefaultAccessLevelEnum {
    Admin = 'admin',
    Editor = 'editor',
    User = 'user'
}
/**
    * @export
    * @enum {string}
    */
export enum CustomFieldResponseAllOfResourceSubtypeEnum {
    Text = 'text',
    Enum = 'enum',
    MultiEnum = 'multi_enum',
    Number = 'number',
    Date = 'date',
    People = 'people',
    Reference = 'reference'
}


