/* tslint:disable */
/* eslint-disable */
/**
 * Asana
 * This is the interface for interacting with the [Asana Platform](https://developers.asana.com). Our API reference is generated from our [OpenAPI spec] (https://raw.githubusercontent.com/Asana/openapi/master/defs/asana_oas.yaml).
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { EnumOption } from './enum-option';

/**
 * 
 * @export
 * @interface CustomFieldBaseAllOf
 */
export interface CustomFieldBaseAllOf {
    /**
     * [Opt In](/docs/inputoutput-options). The description of the custom field.
     * @type {string}
     * @memberof CustomFieldBaseAllOf
     */
    'description'?: string;
    /**
     * *Conditional*. Only relevant for custom fields of type `enum`. This array specifies the possible values which an `enum` custom field can adopt. To modify the enum options, refer to [working with enum options](/reference/createenumoptionforcustomfield).
     * @type {Array<EnumOption>}
     * @memberof CustomFieldBaseAllOf
     */
    'enum_options'?: Array<EnumOption>;
    /**
     * Only relevant for custom fields of type ‘Number’. This field dictates the number of places after the decimal to round to, i.e. 0 is integer values, 1 rounds to the nearest tenth, and so on. Must be between 0 and 6, inclusive. For percentage format, this may be unintuitive, as a value of 0.25 has a precision of 0, while a value of 0.251 has a precision of 1. This is due to 0.25 being displayed as 25%. The identifier format will always have a precision of 0.
     * @type {number}
     * @memberof CustomFieldBaseAllOf
     */
    'precision'?: number;
    /**
     * The format of this custom field.
     * @type {string}
     * @memberof CustomFieldBaseAllOf
     */
    'format'?: CustomFieldBaseAllOfFormatEnum;
    /**
     * ISO 4217 currency code to format this custom field. This will be null if the `format` is not `currency`.
     * @type {string}
     * @memberof CustomFieldBaseAllOf
     */
    'currency_code'?: string | null;
    /**
     * This is the string that appears next to the custom field value. This will be null if the `format` is not `custom`.
     * @type {string}
     * @memberof CustomFieldBaseAllOf
     */
    'custom_label'?: string | null;
    /**
     * Only relevant for custom fields with `custom` format. This depicts where to place the custom label. This will be null if the `format` is not `custom`.
     * @type {string}
     * @memberof CustomFieldBaseAllOf
     */
    'custom_label_position'?: CustomFieldBaseAllOfCustomLabelPositionEnum;
    /**
     * This flag describes whether this custom field is available to every container in the workspace. Before project-specific custom fields, this field was always true.
     * @type {boolean}
     * @memberof CustomFieldBaseAllOf
     */
    'is_global_to_workspace'?: boolean;
    /**
     * *Conditional*. This flag describes whether a follower of a task with this field should receive inbox notifications from changes to this field.
     * @type {boolean}
     * @memberof CustomFieldBaseAllOf
     */
    'has_notifications_enabled'?: boolean;
    /**
     * *Conditional*. A unique identifier to associate this field with the template source of truth.
     * @type {string}
     * @memberof CustomFieldBaseAllOf
     */
    'asana_created_field'?: CustomFieldBaseAllOfAsanaCreatedFieldEnum;
}

/**
    * @export
    * @enum {string}
    */
export enum CustomFieldBaseAllOfFormatEnum {
    Currency = 'currency',
    Identifier = 'identifier',
    Percentage = 'percentage',
    Custom = 'custom',
    Duration = 'duration',
    None = 'none'
}
/**
    * @export
    * @enum {string}
    */
export enum CustomFieldBaseAllOfCustomLabelPositionEnum {
    Prefix = 'prefix',
    Suffix = 'suffix',
    Null = 'null'
}
/**
    * @export
    * @enum {string}
    */
export enum CustomFieldBaseAllOfAsanaCreatedFieldEnum {
    AVRequirements = 'a_v_requirements',
    AccountName = 'account_name',
    Actionable = 'actionable',
    AlignShippingLink = 'align_shipping_link',
    AlignStatus = 'align_status',
    AllottedTime = 'allotted_time',
    Appointment = 'appointment',
    ApprovalStage = 'approval_stage',
    Approved = 'approved',
    ArticleSeries = 'article_series',
    BoardCommittee = 'board_committee',
    Browser = 'browser',
    CampaignAudience = 'campaign_audience',
    CampaignProjectStatus = 'campaign_project_status',
    CampaignRegions = 'campaign_regions',
    ChannelPrimary = 'channel_primary',
    ClientTopicType = 'client_topic_type',
    CompleteBy = 'complete_by',
    Contact = 'contact',
    ContactEmailAddress = 'contact_email_address',
    ContentChannels = 'content_channels',
    ContentChannelsNeeded = 'content_channels_needed',
    ContentStage = 'content_stage',
    ContentType = 'content_type',
    Contract = 'contract',
    ContractStatus = 'contract_status',
    Cost = 'cost',
    CreationStage = 'creation_stage',
    CreativeChannel = 'creative_channel',
    CreativeNeeded = 'creative_needed',
    CreativeNeeds = 'creative_needs',
    DataSensitivity = 'data_sensitivity',
    DealSize = 'deal_size',
    DeliveryAppt = 'delivery_appt',
    DeliveryApptDate = 'delivery_appt_date',
    Department = 'department',
    DepartmentResponsible = 'department_responsible',
    DesignRequestNeeded = 'design_request_needed',
    DesignRequestType = 'design_request_type',
    DiscussionCategory = 'discussion_category',
    DoThisTask = 'do_this_task',
    EditorialContentStatus = 'editorial_content_status',
    EditorialContentTag = 'editorial_content_tag',
    EditorialContentType = 'editorial_content_type',
    Effort = 'effort',
    EffortLevel = 'effort_level',
    EstCompletionDate = 'est_completion_date',
    EstimatedTime = 'estimated_time',
    EstimatedValue = 'estimated_value',
    ExpectedCost = 'expected_cost',
    ExternalStepsNeeded = 'external_steps_needed',
    FavoriteIdea = 'favorite_idea',
    FeedbackType = 'feedback_type',
    Financial = 'financial',
    FundingAmount = 'funding_amount',
    GrantApplicationProcess = 'grant_application_process',
    HiringCandidateStatus = 'hiring_candidate_status',
    IdeaStatus = 'idea_status',
    IdsLink = 'ids_link',
    IdsPatientLink = 'ids_patient_link',
    ImplementationStage = 'implementation_stage',
    Insurance = 'insurance',
    InterviewArea = 'interview_area',
    InterviewQuestionScore = 'interview_question_score',
    IteroScanLink = 'itero_scan_link',
    JobSAppliedTo = 'job_s_applied_to',
    Lab = 'lab',
    LaunchStatus = 'launch_status',
    LeadStatus = 'lead_status',
    LocalizationLanguage = 'localization_language',
    LocalizationMarketTeam = 'localization_market_team',
    LocalizationStatus = 'localization_status',
    MeetingMinutes = 'meeting_minutes',
    MeetingNeeded = 'meeting_needed',
    Minutes = 'minutes',
    Mrr = 'mrr',
    MustLocalize = 'must_localize',
    NameOfFoundation = 'name_of_foundation',
    NeedToFollowUp = 'need_to_follow_up',
    NextAppointment = 'next_appointment',
    NextStepsSales = 'next_steps_sales',
    NumPeople = 'num_people',
    NumberOfUserReports = 'number_of_user_reports',
    OfficeLocation = 'office_location',
    OnboardingActivity = 'onboarding_activity',
    Owner = 'owner',
    ParticipantsNeeded = 'participants_needed',
    PatientDateOfBirth = 'patient_date_of_birth',
    PatientEmail = 'patient_email',
    PatientPhone = 'patient_phone',
    PatientStatus = 'patient_status',
    PhoneNumber = 'phone_number',
    PlanningCategory = 'planning_category',
    PointOfContact = 'point_of_contact',
    Position = 'position',
    PostFormat = 'post_format',
    Prescription = 'prescription',
    Priority = 'priority',
    PriorityLevel = 'priority_level',
    Product = 'product',
    ProductStage = 'product_stage',
    Progress = 'progress',
    ProjectSize = 'project_size',
    ProjectStatus = 'project_status',
    ProposedBudget = 'proposed_budget',
    PublishStatus = 'publish_status',
    ReasonForScan = 'reason_for_scan',
    Referral = 'referral',
    RequestType = 'request_type',
    ResearchStatus = 'research_status',
    ResponsibleDepartment = 'responsible_department',
    ResponsibleTeam = 'responsible_team',
    RiskAssessmentStatus = 'risk_assessment_status',
    RoomName = 'room_name',
    SalesCounterpart = 'sales_counterpart',
    Sentiment = 'sentiment',
    ShippingLink = 'shipping_link',
    SocialChannels = 'social_channels',
    Stage = 'stage',
    Status = 'status',
    StatusDesign = 'status_design',
    StatusOfInitiative = 'status_of_initiative',
    SystemSetup = 'system_setup',
    TaskProgress = 'task_progress',
    Team = 'team',
    TeamMarketing = 'team_marketing',
    TeamResponsible = 'team_responsible',
    TimeItTakesToCompleteTasks = 'time_it_takes_to_complete_tasks',
    Timeframe = 'timeframe',
    TreatmentType = 'treatment_type',
    TypeWorkRequestsIt = 'type_work_requests_it',
    UseAgency = 'use_agency',
    UserName = 'user_name',
    VendorCategory = 'vendor_category',
    VendorType = 'vendor_type',
    WordCount = 'word_count',
    Null = 'null'
}


