/* tslint:disable */
/* eslint-disable */
/**
 * Asana
 * This is the interface for interacting with the [Asana Platform](https://developers.asana.com). Our API reference is generated from our [OpenAPI spec] (https://raw.githubusercontent.com/Asana/openapi/master/defs/asana_oas.yaml).
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { CustomFieldCompactDateValue } from './custom-field-compact-date-value';
import { EnumOption } from './enum-option';

/**
 * Custom Fields store the metadata that is used in order to add user-specified information to tasks in Asana. Be sure to reference the [custom fields](/reference/custom-fields) developer documentation for more information about how custom fields relate to various resources in Asana.  Users in Asana can [lock custom fields](https://asana.com/guide/help/premium/custom-fields#gl-lock-fields), which will make them read-only when accessed by other users. Attempting to edit a locked custom field will return HTTP error code `403 Forbidden`.
 * @export
 * @interface CustomFieldCompact
 */
export interface CustomFieldCompact {
    /**
     * Globally unique identifier of the resource, as a string.
     * @type {string}
     * @memberof CustomFieldCompact
     */
    'gid'?: string;
    /**
     * The base type of this resource.
     * @type {string}
     * @memberof CustomFieldCompact
     */
    'resource_type'?: string;
    /**
     * The name of the custom field.
     * @type {string}
     * @memberof CustomFieldCompact
     */
    'name'?: string;
    /**
     * *Deprecated: new integrations should prefer the resource_subtype field.* The type of the custom field. Must be one of the given values. 
     * @type {string}
     * @memberof CustomFieldCompact
     */
    'type'?: CustomFieldCompactTypeEnum;
    /**
     * *Conditional*. Only relevant for custom fields of type `enum` or `multi_enum`. This array specifies the possible values which an `enum` custom field can adopt. To modify the enum options, refer to [working with enum options](/reference/createenumoptionforcustomfield).
     * @type {Array<EnumOption>}
     * @memberof CustomFieldCompact
     */
    'enum_options'?: Array<EnumOption>;
    /**
     * *Conditional*. This field applies only to [custom field values](/docs/custom-fields-guide#/accessing-custom-field-values-on-tasks-or-projects) and is not available for [custom field definitions](/docs/custom-fields-guide#/accessing-custom-field-definitions). Determines if the custom field is enabled or not. For more details, see the [Custom Fields documentation](/docs/custom-fields-guide#/enabled-and-disabled-values).
     * @type {boolean}
     * @memberof CustomFieldCompact
     */
    'enabled'?: boolean;
    /**
     * This field tells the type of the custom field.
     * @type {string}
     * @memberof CustomFieldCompact
     */
    'representation_type'?: CustomFieldCompactRepresentationTypeEnum;
    /**
     * This field is the unique custom ID string for the custom field.
     * @type {string}
     * @memberof CustomFieldCompact
     */
    'id_prefix'?: string | null;
    /**
     * 
     * @type {Array<string>}
     * @memberof CustomFieldCompact
     */
    'input_restrictions'?: Array<CustomFieldCompactInputRestrictionsEnum>;
    /**
     * *Conditional*. This flag describes whether a custom field is a formula custom field.
     * @type {boolean}
     * @memberof CustomFieldCompact
     */
    'is_formula_field'?: boolean;
    /**
     * 
     * @type {CustomFieldCompactDateValue}
     * @memberof CustomFieldCompact
     */
    'date_value'?: CustomFieldCompactDateValue | null;
    /**
     * 
     * @type {EnumOption & object}
     * @memberof CustomFieldCompact
     */
    'enum_value'?: EnumOption & object;
    /**
     * *Conditional*. Only relevant for custom fields of type `multi_enum`. This object is the chosen values of a `multi_enum` custom field.
     * @type {Array<EnumOption>}
     * @memberof CustomFieldCompact
     */
    'multi_enum_values'?: Array<EnumOption>;
    /**
     * *Conditional*. This number is the value of a `number` custom field.
     * @type {number}
     * @memberof CustomFieldCompact
     */
    'number_value'?: number | null;
    /**
     * *Conditional*. This string is the value of a `text` custom field.
     * @type {string}
     * @memberof CustomFieldCompact
     */
    'text_value'?: string | null;
    /**
     * A string representation for the value of the custom field. Integrations that don\'t require the underlying type should use this field to read values. Using this field will future-proof an app against new custom field types.
     * @type {string}
     * @memberof CustomFieldCompact
     */
    'display_value'?: string | null;
}

/**
    * @export
    * @enum {string}
    */
export enum CustomFieldCompactTypeEnum {
    Text = 'text',
    Enum = 'enum',
    MultiEnum = 'multi_enum',
    Number = 'number',
    Date = 'date',
    People = 'people',
    Reference = 'reference'
}
/**
    * @export
    * @enum {string}
    */
export enum CustomFieldCompactRepresentationTypeEnum {
    Text = 'text',
    Enum = 'enum',
    MultiEnum = 'multi_enum',
    Number = 'number',
    Date = 'date',
    People = 'people',
    Formula = 'formula',
    CustomId = 'custom_id',
    Reference = 'reference'
}
/**
    * @export
    * @enum {string}
    */
export enum CustomFieldCompactInputRestrictionsEnum {
    Task = 'task',
    Project = 'project',
    Portfolio = 'portfolio',
    Goal = 'goal'
}


