/* tslint:disable */
/* eslint-disable */
/**
 * Asana
 * This is the interface for interacting with the [Asana Platform](https://developers.asana.com). Our API reference is generated from our [OpenAPI spec] (https://raw.githubusercontent.com/Asana/openapi/master/defs/asana_oas.yaml).
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface CustomFieldRequestAllOf
 */
export interface CustomFieldRequestAllOf {
    /**
     * *Create-Only* The workspace to create a custom field in.
     * @type {string}
     * @memberof CustomFieldRequestAllOf
     */
    'workspace': string;
    /**
     * *Allow-listed*. Instructs the API that this Custom Field is app-owned. This parameter is allow-listed to specific apps at this point in time. For apps that are not allow-listed, providing this parameter will result in a `403 Forbidden`.
     * @type {boolean}
     * @memberof CustomFieldRequestAllOf
     */
    'owned_by_app'?: boolean;
    /**
     * *Conditional*. Only relevant for custom fields of type `people`. This array of user GIDs, emails, or the string \"me\", reflects the users to be written to a `people` custom field. Note that *write* operations will replace existing users (if any) in the custom field with the users specified in this array.
     * @type {Array<string>}
     * @memberof CustomFieldRequestAllOf
     */
    'people_value'?: Array<string>;
    /**
     * *Conditional*. Only relevant for custom fields of type `reference`. This array of GIDs reflects the objects to be written to a `reference` custom field. Note that *write* operations will replace existing objects (if any) in the custom field with the objects specified in this array.
     * @type {Array<string>}
     * @memberof CustomFieldRequestAllOf
     */
    'reference_value'?: Array<string>;
}

