/* tslint:disable */
/* eslint-disable */
/**
 * Asana
 * This is the interface for interacting with the [Asana Platform](https://developers.asana.com). Our API reference is generated from our [OpenAPI spec] (https://raw.githubusercontent.com/Asana/openapi/master/defs/asana_oas.yaml).
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { GoalCompact } from './goal-compact';
import { MemberCompact } from './member-compact';

/**
 * This object represents a user\'s connection to a goal.
 * @export
 * @interface GoalMembershipBaseAllOf
 */
export interface GoalMembershipBaseAllOf {
    /**
     * The type of membership.
     * @type {string}
     * @memberof GoalMembershipBaseAllOf
     */
    'resource_subtype'?: string;
    /**
     * 
     * @type {MemberCompact}
     * @memberof GoalMembershipBaseAllOf
     */
    'member'?: MemberCompact;
    /**
     * 
     * @type {GoalCompact & object}
     * @memberof GoalMembershipBaseAllOf
     */
    'parent'?: GoalCompact & object;
    /**
     * Describes if the member is a commenter or editor in goal.
     * @type {string}
     * @memberof GoalMembershipBaseAllOf
     */
    'role'?: GoalMembershipBaseAllOfRoleEnum;
    /**
     * 
     * @type {GoalCompact & object}
     * @memberof GoalMembershipBaseAllOf
     */
    'goal'?: GoalCompact & object;
}

/**
    * @export
    * @enum {string}
    */
export enum GoalMembershipBaseAllOfRoleEnum {
    Commenter = 'commenter',
    Editor = 'editor'
}


