/* tslint:disable */
/* eslint-disable */
/**
 * Asana
 * This is the interface for interacting with the [Asana Platform](https://developers.asana.com). Our API reference is generated from our [OpenAPI spec] (https://raw.githubusercontent.com/Asana/openapi/master/defs/asana_oas.yaml).
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { GoalMetricBase } from './goal-metric-base';
import { Like } from './like';
import { StatusUpdateCompact } from './status-update-compact';
import { TeamCompact } from './team-compact';
import { TimePeriodCompact } from './time-period-compact';
import { UserCompact } from './user-compact';
import { WorkspaceCompact } from './workspace-compact';

/**
 * 
 * @export
 * @interface GoalResponseAllOf
 */
export interface GoalResponseAllOf {
    /**
     * Array of likes for users who have liked this goal.
     * @type {Array<Like>}
     * @memberof GoalResponseAllOf
     */
    'likes'?: Array<Like>;
    /**
     * The number of users who have liked this goal.
     * @type {number}
     * @memberof GoalResponseAllOf
     */
    'num_likes'?: number;
    /**
     * 
     * @type {TeamCompact & object}
     * @memberof GoalResponseAllOf
     */
    'team'?: TeamCompact & object;
    /**
     * 
     * @type {WorkspaceCompact & object}
     * @memberof GoalResponseAllOf
     */
    'workspace'?: WorkspaceCompact & object;
    /**
     * Array of users who are members of this goal.
     * @type {Array<UserCompact>}
     * @memberof GoalResponseAllOf
     */
    'followers'?: Array<UserCompact>;
    /**
     * 
     * @type {TimePeriodCompact & object}
     * @memberof GoalResponseAllOf
     */
    'time_period'?: TimePeriodCompact & object;
    /**
     * 
     * @type {GoalMetricBase & object}
     * @memberof GoalResponseAllOf
     */
    'metric'?: GoalMetricBase & object;
    /**
     * 
     * @type {UserCompact & object}
     * @memberof GoalResponseAllOf
     */
    'owner'?: UserCompact & object;
    /**
     * 
     * @type {StatusUpdateCompact}
     * @memberof GoalResponseAllOf
     */
    'current_status_update'?: StatusUpdateCompact;
    /**
     * The current status of this goal. When the goal is open, its status can be `green`, `yellow`, and `red` to reflect \"On Track\", \"At Risk\", and \"Off Track\", respectively. When the goal is closed, the value can be `missed`, `achieved`, `partial`, or `dropped`. *Note* you can only write to this property if `metric` is set.
     * @type {string}
     * @memberof GoalResponseAllOf
     */
    'status'?: string | null;
}

