/* tslint:disable */
/* eslint-disable */
/**
 * Asana
 * This is the interface for interacting with the [Asana Platform](https://developers.asana.com). Our API reference is generated from our [OpenAPI spec] (https://raw.githubusercontent.com/Asana/openapi/master/defs/asana_oas.yaml).
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { UserCompact } from './user-compact';

/**
 * A generic Asana Resource, containing a globally unique identifier.
 * @export
 * @interface GoalCompact
 */
export interface GoalCompact {
    /**
     * Globally unique identifier of the resource, as a string.
     * @type {string}
     * @memberof GoalCompact
     */
    'gid'?: string;
    /**
     * The base type of this resource.
     * @type {string}
     * @memberof GoalCompact
     */
    'resource_type'?: string;
    /**
     * The name of the goal.
     * @type {string}
     * @memberof GoalCompact
     */
    'name'?: string;
    /**
     * 
     * @type {UserCompact & object}
     * @memberof GoalCompact
     */
    'owner'?: UserCompact & object;
}

