/* tslint:disable */
/* eslint-disable */
/**
 * Asana
 * This is the interface for interacting with the [Asana Platform](https://developers.asana.com). Our API reference is generated from our [OpenAPI spec] (https://raw.githubusercontent.com/Asana/openapi/master/defs/asana_oas.yaml).
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * A *graph_export* object represents a request to export the data starting from a parent object
 * @export
 * @interface GraphExportCompact
 */
export interface GraphExportCompact {
    /**
     * Globally unique identifier of the resource, as a string.
     * @type {string}
     * @memberof GraphExportCompact
     */
    'gid'?: string;
    /**
     * The base type of this resource.
     * @type {string}
     * @memberof GraphExportCompact
     */
    'resource_type'?: string;
    /**
     * The time at which this resource was created.
     * @type {string}
     * @memberof GraphExportCompact
     */
    'created_at'?: string;
    /**
     * Download this URL to retrieve the full export in JSON format. It will be compressed in a gzip (.gz) container.  *Note: May be null if the export is still in progress or failed.  If present, this URL may only be valid for 1 hour from the time of retrieval. You should avoid persisting this URL somewhere and rather refresh on demand to ensure you do not keep stale URLs.*
     * @type {string}
     * @memberof GraphExportCompact
     */
    'download_url'?: string | null;
    /**
     * The time at which this resource was completed.
     * @type {string}
     * @memberof GraphExportCompact
     */
    'completed_at'?: string;
}

