/* tslint:disable */
/* eslint-disable */
/**
 * Asana
 * This is the interface for interacting with the [Asana Platform](https://developers.asana.com). Our API reference is generated from our [OpenAPI spec] (https://raw.githubusercontent.com/Asana/openapi/master/defs/asana_oas.yaml).
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { GraphExportCompact } from './graph-export-compact';

/**
 * A generic Asana Resource, containing a globally unique identifier.
 * @export
 * @interface GraphExportResponse
 */
export interface GraphExportResponse {
    /**
     * Globally unique identifier of the resource, as a string.
     * @type {string}
     * @memberof GraphExportResponse
     */
    'gid'?: string;
    /**
     * The base type of this resource.
     * @type {string}
     * @memberof GraphExportResponse
     */
    'resource_type'?: string;
    /**
     * A *graph_export* object represents a request to export the data starting from a parent object
     * @type {string}
     * @memberof GraphExportResponse
     */
    'resource_subtype'?: string;
    /**
     * The current status of this job.
     * @type {string}
     * @memberof GraphExportResponse
     */
    'status'?: GraphExportResponseStatusEnum;
    /**
     * 
     * @type {GraphExportCompact}
     * @memberof GraphExportResponse
     */
    'new_graph_export'?: GraphExportCompact;
}

/**
    * @export
    * @enum {string}
    */
export enum GraphExportResponseStatusEnum {
    NotStarted = 'not_started',
    InProgress = 'in_progress',
    Succeeded = 'succeeded',
    Failed = 'failed'
}


