/* tslint:disable */
/* eslint-disable */
/**
 * Asana
 * This is the interface for interacting with the [Asana Platform](https://developers.asana.com). Our API reference is generated from our [OpenAPI spec] (https://raw.githubusercontent.com/Asana/openapi/master/defs/asana_oas.yaml).
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { AuditLogEvent } from './audit-log-event';
import { NextPage } from './next-page';

/**
 * 
 * @export
 * @interface InlineResponse2008
 */
export interface InlineResponse2008 {
    /**
     * 
     * @type {Array<AuditLogEvent>}
     * @memberof InlineResponse2008
     */
    'data'?: Array<AuditLogEvent>;
    /**
     * 
     * @type {NextPage}
     * @memberof InlineResponse2008
     */
    'next_page'?: NextPage | null;
}

