/* tslint:disable */
/* eslint-disable */
/**
 * Asana
 * This is the interface for interacting with the [Asana Platform](https://developers.asana.com). Our API reference is generated from our [OpenAPI spec] (https://raw.githubusercontent.com/Asana/openapi/master/defs/asana_oas.yaml).
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { EventResponse } from './event-response';

/**
 * The full record for all events that have occurred since the sync token was created.
 * @export
 * @interface InlineResponse2007
 */
export interface InlineResponse2007 {
    /**
     * 
     * @type {Array<EventResponse>}
     * @memberof InlineResponse2007
     */
    'data'?: Array<EventResponse>;
    /**
     * A sync token to be used with the next call to the /events endpoint.
     * @type {string}
     * @memberof InlineResponse2007
     */
    'sync'?: string;
    /**
     * Indicates whether there are more events to pull.
     * @type {boolean}
     * @memberof InlineResponse2007
     */
    'has_more'?: boolean;
}

