/* tslint:disable */
/* eslint-disable */
/**
 * Asana
 * This is the interface for interacting with the [Asana Platform](https://developers.asana.com). Our API reference is generated from our [OpenAPI spec] (https://raw.githubusercontent.com/Asana/developer-docs/master/defs/asana_oas.yaml).
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { TeamRemoveUserRequest } from './team-remove-user-request';

/**
 * 
 * @export
 * @interface InlineObject62
 */
export interface InlineObject62 {
    /**
     * 
     * @type {TeamRemoveUserRequest}
     * @memberof InlineObject62
     */
    'data'?: TeamRemoveUserRequest;
}

