/* tslint:disable */
/* eslint-disable */
/**
 * Asana
 * This is the interface for interacting with the [Asana Platform](https://developers.asana.com). Our API reference is generated from our [OpenAPI spec] (https://raw.githubusercontent.com/Asana/developer-docs/master/defs/asana_oas.yaml).
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { ProjectCompact } from './project-compact';
import { ProjectTemplateCompact } from './project-template-compact';
import { TaskCompact } from './task-compact';

/**
 * A *job* is an object representing a process that handles asynchronous work.
 * @export
 * @interface JobCompactAllOf
 */
export interface JobCompactAllOf {
    /**
     * The subtype of this resource. Different subtypes retain many of the same fields and behavior, but may render differently in Asana or represent resources with different semantic meaning.
     * @type {string}
     * @memberof JobCompactAllOf
     */
    'resource_subtype'?: string;
    /**
     * The current status of this job. The value is one of: `not_started`, `in_progress`, `succeeded`, or `failed`.
     * @type {string}
     * @memberof JobCompactAllOf
     */
    'status'?: JobCompactAllOfStatusEnum;
    /**
     * 
     * @type {ProjectCompact}
     * @memberof JobCompactAllOf
     */
    'new_project'?: ProjectCompact;
    /**
     * 
     * @type {TaskCompact}
     * @memberof JobCompactAllOf
     */
    'new_task'?: TaskCompact;
    /**
     * 
     * @type {ProjectTemplateCompact}
     * @memberof JobCompactAllOf
     */
    'new_project_template'?: ProjectTemplateCompact;
}

/**
    * @export
    * @enum {string}
    */
export enum JobCompactAllOfStatusEnum {
    NotStarted = 'not_started',
    InProgress = 'in_progress',
    Succeeded = 'succeeded',
    Failed = 'failed'
}


