/* tslint:disable */
/* eslint-disable */
/**
 * Asana
 * This is the interface for interacting with the [Asana Platform](https://developers.asana.com). Our API reference is generated from our [OpenAPI spec] (https://raw.githubusercontent.com/Asana/openapi/master/defs/asana_oas.yaml).
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { GoalCompact } from './goal-compact';
import { GoalMembershipCompact } from './goal-membership-compact';
import { MemberCompact } from './member-compact';

/**
 * 
 * @export
 * @interface MembershipResponse
 */
export interface MembershipResponse {
    /**
     * Globally unique identifier of the resource, as a string.
     * @type {string}
     * @memberof MembershipResponse
     */
    'gid'?: string;
    /**
     * The base type of this resource.
     * @type {string}
     * @memberof MembershipResponse
     */
    'resource_type'?: string;
    /**
     * 
     * @type {MemberCompact}
     * @memberof MembershipResponse
     */
    'member'?: MemberCompact;
    /**
     * 
     * @type {GoalCompact}
     * @memberof MembershipResponse
     */
    'goal'?: GoalCompact;
    /**
     * Describes if the member is comment only in goal.
     * @type {boolean}
     * @memberof MembershipResponse
     */
    'is_commenter'?: boolean;
    /**
     * Describes if the member is editor in goal.
     * @type {boolean}
     * @memberof MembershipResponse
     */
    'is_editor'?: boolean;
}

