/* tslint:disable */
/* eslint-disable */
/**
 * Asana
 * This is the interface for interacting with the [Asana Platform](https://developers.asana.com). Our API reference is generated from our [OpenAPI spec] (https://raw.githubusercontent.com/Asana/openapi/master/defs/asana_oas.yaml).
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * A *member* object represents either a team or user.
 * @export
 * @interface MemberCompact
 */
export interface MemberCompact {
    /**
     * Globally unique identifier of the resource, as a string.
     * @type {string}
     * @memberof MemberCompact
     */
    'gid'?: string;
    /**
     * The type of the member (team or user)
     * @type {string}
     * @memberof MemberCompact
     */
    'resource_type'?: string;
    /**
     * The name of the member
     * @type {string}
     * @memberof MemberCompact
     */
    'name'?: string;
}

