/* tslint:disable */
/* eslint-disable */
/**
 * Asana
 * This is the interface for interacting with the [Asana Platform](https://developers.asana.com). Our API reference is generated from our [OpenAPI spec] (https://raw.githubusercontent.com/Asana/openapi/master/defs/asana_oas.yaml).
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * A generic Asana Resource, containing a globally unique identifier.
 * @export
 * @interface OooEntryBase
 */
export interface OooEntryBase {
    /**
     * Globally unique identifier of the resource, as a string.
     * @type {string}
     * @memberof OooEntryBase
     */
    'gid'?: string;
    /**
     * The base type of this resource.
     * @type {string}
     * @memberof OooEntryBase
     */
    'resource_type'?: string;
    /**
     * The day on which the OOO entry starts.
     * @type {string}
     * @memberof OooEntryBase
     */
    'start_date'?: string;
    /**
     * The day on which the OOO entry ends.
     * @type {string}
     * @memberof OooEntryBase
     */
    'end_date'?: string;
}

