/* tslint:disable */
/* eslint-disable */
/**
 * Asana
 * This is the interface for interacting with the [Asana Platform](https://developers.asana.com). Our API reference is generated from our [OpenAPI spec] (https://raw.githubusercontent.com/Asana/openapi/master/defs/asana_oas.yaml).
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * A *placeholder* object represents a placeholder in Asana that can be used to represent a placeholder user.
 * @export
 * @interface PlaceholderCompact
 */
export interface PlaceholderCompact {
    /**
     * Globally unique identifier of the resource, as a string.
     * @type {string}
     * @memberof PlaceholderCompact
     */
    'gid'?: string;
    /**
     * The base type of this resource.
     * @type {string}
     * @memberof PlaceholderCompact
     */
    'resource_type'?: string;
    /**
     * The placeholder\'s name.
     * @type {string}
     * @memberof PlaceholderCompact
     */
    'name'?: string;
}

