/* tslint:disable */
/* eslint-disable */
/**
 * Asana
 * This is the interface for interacting with the [Asana Platform](https://developers.asana.com). Our API reference is generated from our [OpenAPI spec] (https://raw.githubusercontent.com/Asana/openapi/master/defs/asana_oas.yaml).
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { DateVariableCompact } from './date-variable-compact';
import { ProjectTemplateBaseAllOf } from './project-template-base-all-of';
import { ProjectTemplateCompact } from './project-template-compact';
import { TeamCompact } from './team-compact';
import { TemplateRole } from './template-role';
import { UserCompact } from './user-compact';

/**
 * @type ProjectTemplateBase
 * @export
 */
export type ProjectTemplateBase = ProjectTemplateBaseAllOf & ProjectTemplateCompact;


