/* tslint:disable */
/* eslint-disable */
/**
 * Asana
 * This is the interface for interacting with the [Asana Platform](https://developers.asana.com). Our API reference is generated from our [OpenAPI spec] (https://raw.githubusercontent.com/Asana/openapi/master/defs/asana_oas.yaml).
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { ProjectCompact } from './project-compact';

/**
 * 
 * @export
 * @interface ProjectBriefResponseAllOf
 */
export interface ProjectBriefResponseAllOf {
    /**
     * [Opt In](/docs/inputoutput-options). The plain text of the project brief.
     * @type {string}
     * @memberof ProjectBriefResponseAllOf
     */
    'text'?: string;
    /**
     * A url that points directly to the object within Asana.
     * @type {string}
     * @memberof ProjectBriefResponseAllOf
     */
    'permalink_url'?: string;
    /**
     * 
     * @type {ProjectCompact & object}
     * @memberof ProjectBriefResponseAllOf
     */
    'project'?: ProjectCompact & object;
}

