/* tslint:disable */
/* eslint-disable */
/**
 * Asana
 * This is the interface for interacting with the [Asana Platform](https://developers.asana.com). Our API reference is generated from our [OpenAPI spec] (https://raw.githubusercontent.com/Asana/openapi/master/defs/asana_oas.yaml).
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { MemberCompact } from './member-compact';
import { ProjectCompact } from './project-compact';

/**
 * This object describes a team or a user\'s membership to a project including their level of access (Admin, Editor, Commenter, or Viewer).
 * @export
 * @interface ProjectMembershipCompactAllOf
 */
export interface ProjectMembershipCompactAllOf {
    /**
     * 
     * @type {ProjectCompact}
     * @memberof ProjectMembershipCompactAllOf
     */
    'parent'?: ProjectCompact;
    /**
     * 
     * @type {MemberCompact}
     * @memberof ProjectMembershipCompactAllOf
     */
    'member'?: MemberCompact;
    /**
     * Whether the member has admin, editor, commenter, or viewer access to the project.
     * @type {string}
     * @memberof ProjectMembershipCompactAllOf
     */
    'access_level'?: ProjectMembershipCompactAllOfAccessLevelEnum;
}

/**
    * @export
    * @enum {string}
    */
export enum ProjectMembershipCompactAllOfAccessLevelEnum {
    Admin = 'admin',
    Editor = 'editor',
    Commenter = 'commenter',
    Viewer = 'viewer'
}


