/* tslint:disable */
/* eslint-disable */
/**
 * Asana
 * This is the interface for interacting with the [Asana Platform](https://developers.asana.com). Our API reference is generated from our [OpenAPI spec] (https://raw.githubusercontent.com/Asana/openapi/master/defs/asana_oas.yaml).
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * A *resource_export* object represents a request to bulk export objects for one or more resources.
 * @export
 * @interface ResourceExportCompact
 */
export interface ResourceExportCompact {
    /**
     * Globally unique identifier of the resource, as a string.
     * @type {string}
     * @memberof ResourceExportCompact
     */
    'gid'?: string;
    /**
     * The base type of this resource.
     * @type {string}
     * @memberof ResourceExportCompact
     */
    'resource_type'?: string;
    /**
     * The time at which the resource export object was created.
     * @type {string}
     * @memberof ResourceExportCompact
     */
    'created_at'?: string;
    /**
     * Download this URL to retrieve the full export in [JSON Lines](https://jsonlines.org/) format. It will be compressed in a gzip (.gz) container.  *Note: May be null if the export is still in progress or failed.*
     * @type {string}
     * @memberof ResourceExportCompact
     */
    'download_url'?: string | null;
    /**
     * The time at which this resource was completed. This will be null if the export is still in progress.
     * @type {string}
     * @memberof ResourceExportCompact
     */
    'completed_at'?: string;
}

