/* tslint:disable */
/* eslint-disable */
/**
 * Asana
 * This is the interface for interacting with the [Asana Platform](https://developers.asana.com). Our API reference is generated from our [OpenAPI spec] (https://raw.githubusercontent.com/Asana/openapi/master/defs/asana_oas.yaml).
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { UserCompact } from './user-compact';

/**
 * A story represents an activity associated with an object in the Asana system.
 * @export
 * @interface StoryCompactAllOf
 */
export interface StoryCompactAllOf {
    /**
     * The time at which this resource was created.
     * @type {string}
     * @memberof StoryCompactAllOf
     */
    'created_at'?: string;
    /**
     * 
     * @type {UserCompact}
     * @memberof StoryCompactAllOf
     */
    'created_by'?: UserCompact;
    /**
     * The subtype of this resource. Different subtypes retain many of the same fields and behavior, but may render differently in Asana or represent resources with different semantic meaning.
     * @type {string}
     * @memberof StoryCompactAllOf
     */
    'resource_subtype'?: string;
    /**
     * *Create-only*. Human-readable text for the story or comment. This will not include the name of the creator. *Note: This is not guaranteed to be stable for a given type of story. For example, text for a reassignment may not always say “assigned to …” as the text for a story can both be edited and change based on the language settings of the user making the request.* Use the `resource_subtype` property to discover the action that created the story.
     * @type {string}
     * @memberof StoryCompactAllOf
     */
    'text'?: string;
}

