/* tslint:disable */
/* eslint-disable */
/**
 * Asana
 * This is the interface for interacting with the [Asana Platform](https://developers.asana.com). Our API reference is generated from our [OpenAPI spec] (https://raw.githubusercontent.com/Asana/openapi/master/defs/asana_oas.yaml).
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { AttachmentCompact } from './attachment-compact';
import { CustomFieldCompact } from './custom-field-compact';
import { ProjectCompact } from './project-compact';
import { TaskTemplateRecipeCompact } from './task-template-recipe-compact';
import { UserCompact } from './user-compact';

/**
 * 
 * @export
 * @interface TaskTemplateRecipeAllOf
 */
export interface TaskTemplateRecipeAllOf {
    /**
     * Description of the task that will be created from this template.
     * @type {string}
     * @memberof TaskTemplateRecipeAllOf
     */
    'description'?: string;
    /**
     * HTML description of the task that will be created from this template.
     * @type {string}
     * @memberof TaskTemplateRecipeAllOf
     */
    'html_description'?: string;
    /**
     * Array of projects that the task created from this template will be added to
     * @type {Array<ProjectCompact>}
     * @memberof TaskTemplateRecipeAllOf
     */
    'memberships'?: Array<ProjectCompact>;
    /**
     * The number of days after the task has been instantiated on which that the task will start
     * @type {number}
     * @memberof TaskTemplateRecipeAllOf
     */
    'relative_start_on'?: number | null;
    /**
     * The number of days after the task has been instantiated on which that the task will be due
     * @type {number}
     * @memberof TaskTemplateRecipeAllOf
     */
    'relative_due_on'?: number | null;
    /**
     * The time of day that the task will be due
     * @type {string}
     * @memberof TaskTemplateRecipeAllOf
     */
    'due_time'?: string | null;
    /**
     * Array of task templates that the task created from this template will depend on
     * @type {Array<TaskTemplateRecipeCompact>}
     * @memberof TaskTemplateRecipeAllOf
     */
    'dependencies'?: Array<TaskTemplateRecipeCompact>;
    /**
     * Array of task templates that will depend on the task created from this template
     * @type {Array<TaskTemplateRecipeCompact>}
     * @memberof TaskTemplateRecipeAllOf
     */
    'dependents'?: Array<TaskTemplateRecipeCompact>;
    /**
     * Array of users that will be added as followers to the task created from this template
     * @type {Array<UserCompact>}
     * @memberof TaskTemplateRecipeAllOf
     */
    'followers'?: Array<UserCompact>;
    /**
     * Array of attachments that will be added to the task created from this template
     * @type {Array<AttachmentCompact>}
     * @memberof TaskTemplateRecipeAllOf
     */
    'attachments'?: Array<AttachmentCompact>;
    /**
     * Array of subtasks that will be added to the task created from this template
     * @type {Array<TaskTemplateRecipeCompact>}
     * @memberof TaskTemplateRecipeAllOf
     */
    'subtasks'?: Array<TaskTemplateRecipeCompact>;
    /**
     * Array of custom fields that will be added to the task created from this template
     * @type {Array<CustomFieldCompact>}
     * @memberof TaskTemplateRecipeAllOf
     */
    'custom_fields'?: Array<CustomFieldCompact>;
}

