/* tslint:disable */
/* eslint-disable */
/**
 * Asana
 * This is the interface for interacting with the [Asana Platform](https://developers.asana.com). Our API reference is generated from our [OpenAPI spec] (https://raw.githubusercontent.com/Asana/openapi/master/defs/asana_oas.yaml).
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface TaskAddProjectRequest
 */
export interface TaskAddProjectRequest {
    /**
     * The project to add the task to.
     * @type {string}
     * @memberof TaskAddProjectRequest
     */
    'project': string;
    /**
     * A task in the project to insert the task after, or `null` to insert at the beginning of the list. When used with `section`, `null` will insert at the beginning of the specified section, otherwise the task must be in the specified section.
     * @type {string}
     * @memberof TaskAddProjectRequest
     */
    'insert_after'?: string | null;
    /**
     * A task in the project to insert the task before, or `null` to insert at the end of the list. When used with `section`, `null` will insert at the end of the specified section, otherwise the task must be in the specified section.
     * @type {string}
     * @memberof TaskAddProjectRequest
     */
    'insert_before'?: string | null;
    /**
     * A section in the project to insert the task into. The task will be inserted at the bottom of the section unless combined with `insert_before: null` (end of section) or `insert_after: null` (beginning of section). Can also be combined with non-null `insert_before` or `insert_after` to position relative to a task within the section.
     * @type {string}
     * @memberof TaskAddProjectRequest
     */
    'section'?: string | null;
}

