/* tslint:disable */
/* eslint-disable */
/**
 * Asana
 * This is the interface for interacting with the [Asana Platform](https://developers.asana.com). Our API reference is generated from our [OpenAPI spec] (https://raw.githubusercontent.com/Asana/openapi/master/defs/asana_oas.yaml).
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { AsanaResource } from './asana-resource';
import { CustomFieldResponse } from './custom-field-response';
import { Like } from './like';
import { ProjectCompact } from './project-compact';
import { SectionCompact } from './section-compact';
import { TagCompact } from './tag-compact';
import { TaskBase } from './task-base';
import { TaskBaseAllOfExternal } from './task-base-all-of-external';
import { TaskBaseAllOfMemberships } from './task-base-all-of-memberships';
import { TaskCompact } from './task-compact';
import { TaskResponseAllOf } from './task-response-all-of';
import { UserCompact } from './user-compact';
import { WorkspaceCompact } from './workspace-compact';

/**
 * @type TaskResponse
 * @export
 */
export type TaskResponse = TaskBase & TaskResponseAllOf;


