/* tslint:disable */
/* eslint-disable */
/**
 * Asana
 * This is the interface for interacting with the [Asana Platform](https://developers.asana.com). Our API reference is generated from our [OpenAPI spec] (https://raw.githubusercontent.com/Asana/openapi/master/defs/asana_oas.yaml).
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { ProjectCompact } from './project-compact';
import { TaskTemplateBase } from './task-template-base';
import { TaskTemplateRecipe } from './task-template-recipe';
import { TaskTemplateResponseAllOf } from './task-template-response-all-of';
import { UserCompact } from './user-compact';

/**
 * @type TaskTemplateResponse
 * @export
 */
export type TaskTemplateResponse = TaskTemplateBase & TaskTemplateResponseAllOf;


