/* tslint:disable */
/* eslint-disable */
/**
 * Asana
 * This is the interface for interacting with the [Asana Platform](https://developers.asana.com). Our API reference is generated from our [OpenAPI spec] (https://raw.githubusercontent.com/Asana/openapi/master/defs/asana_oas.yaml).
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { AsanaResource } from './asana-resource';
import { Like } from './like';
import { TaskBaseAllOfExternal } from './task-base-all-of-external';
import { TaskBaseAllOfMemberships } from './task-base-all-of-memberships';
import { TaskCompactCreatedBy } from './task-compact-created-by';
import { TaskCreateRequestAllOf } from './task-create-request-all-of';
import { TaskRequestBase } from './task-request-base';
import { UserCompact } from './user-compact';

/**
 * @type TaskCreateRequest
 * @export
 */
export type TaskCreateRequest = TaskCreateRequestAllOf & TaskRequestBase;


