/* tslint:disable */
/* eslint-disable */
/**
 * Asana
 * This is the interface for interacting with the [Asana Platform](https://developers.asana.com). Our API reference is generated from our [OpenAPI spec] (https://raw.githubusercontent.com/Asana/openapi/master/defs/asana_oas.yaml).
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface TaskCreateRequestAllOf
 */
export interface TaskCreateRequestAllOf {
    /**
     * *Create-Only* An array of strings identifying users. These can either be the string \"me\", an email, or the gid of a user. In order to change followers on an existing task use `addFollowers` and `removeFollowers`.
     * @type {Array<string>}
     * @memberof TaskCreateRequestAllOf
     */
    'followers'?: Array<string>;
    /**
     * *Create-Only* Array of project gids. In order to change projects on an existing task use `addProject` and `removeProject`.
     * @type {Array<string>}
     * @memberof TaskCreateRequestAllOf
     */
    'projects'?: Array<string>;
    /**
     * *Create-Only* Array of tag gids. In order to change tags on an existing task use `addTag` and `removeTag`.
     * @type {Array<string>}
     * @memberof TaskCreateRequestAllOf
     */
    'tags'?: Array<string>;
    /**
     * Gid of a workspace.
     * @type {string}
     * @memberof TaskCreateRequestAllOf
     */
    'workspace'?: string;
}

