/* tslint:disable */
/* eslint-disable */
/**
 * Asana
 * This is the interface for interacting with the [Asana Platform](https://developers.asana.com). Our API reference is generated from our [OpenAPI spec] (https://raw.githubusercontent.com/Asana/openapi/master/defs/asana_oas.yaml).
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface TaskTemplateRecipeCompact
 */
export interface TaskTemplateRecipeCompact {
    /**
     * Name of the task that will be created from this template.
     * @type {string}
     * @memberof TaskTemplateRecipeCompact
     */
    'name'?: string;
    /**
     * The subtype of the task that will be created from this template.
     * @type {string}
     * @memberof TaskTemplateRecipeCompact
     */
    'task_resource_subtype'?: TaskTemplateRecipeCompactTaskResourceSubtypeEnum;
}

/**
    * @export
    * @enum {string}
    */
export enum TaskTemplateRecipeCompactTaskResourceSubtypeEnum {
    DefaultTask = 'default_task',
    MilestoneTask = 'milestone_task',
    ApprovalTask = 'approval_task'
}


