/* tslint:disable */
/* eslint-disable */
/**
 * Asana
 * This is the interface for interacting with the [Asana Platform](https://developers.asana.com). Our API reference is generated from our [OpenAPI spec] (https://raw.githubusercontent.com/Asana/openapi/master/defs/asana_oas.yaml).
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { TeamCompact } from './team-compact';
import { UserCompact } from './user-compact';

/**
 * This object represents a user\'s connection to a team.
 * @export
 * @interface TeamMembershipCompact
 */
export interface TeamMembershipCompact {
    /**
     * Globally unique identifier of the resource, as a string.
     * @type {string}
     * @memberof TeamMembershipCompact
     */
    'gid'?: string;
    /**
     * The base type of this resource.
     * @type {string}
     * @memberof TeamMembershipCompact
     */
    'resource_type'?: string;
    /**
     * 
     * @type {UserCompact}
     * @memberof TeamMembershipCompact
     */
    'user'?: UserCompact;
    /**
     * 
     * @type {TeamCompact}
     * @memberof TeamMembershipCompact
     */
    'team'?: TeamCompact;
    /**
     * Describes if the user is a guest in the team.
     * @type {boolean}
     * @memberof TeamMembershipCompact
     */
    'is_guest'?: boolean;
    /**
     * Describes if the user has limited access to the team.
     * @type {boolean}
     * @memberof TeamMembershipCompact
     */
    'is_limited_access'?: boolean;
    /**
     * Describes if the user is a team admin.
     * @type {boolean}
     * @memberof TeamMembershipCompact
     */
    'is_admin'?: boolean;
}

