/* tslint:disable */
/* eslint-disable */
/**
 * Asana
 * This is the interface for interacting with the [Asana Platform](https://developers.asana.com). Our API reference is generated from our [OpenAPI spec] (https://raw.githubusercontent.com/Asana/developer-docs/master/defs/asana_oas.yaml).
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { TeamCompact } from './team-compact';
import { UserCompact } from './user-compact';

/**
 * This object represents a user\'s connection to a team.
 * @export
 * @interface TeamMembershipCompactAllOf
 */
export interface TeamMembershipCompactAllOf {
    /**
     * 
     * @type {UserCompact}
     * @memberof TeamMembershipCompactAllOf
     */
    'user'?: UserCompact;
    /**
     * 
     * @type {TeamCompact}
     * @memberof TeamMembershipCompactAllOf
     */
    'team'?: TeamCompact;
    /**
     * Describes if the user is a guest in the team.
     * @type {boolean}
     * @memberof TeamMembershipCompactAllOf
     */
    'is_guest'?: boolean;
}

