/* tslint:disable */
/* eslint-disable */
/**
 * Asana
 * This is the interface for interacting with the [Asana Platform](https://developers.asana.com). Our API reference is generated from our [OpenAPI spec] (https://raw.githubusercontent.com/Asana/openapi/master/defs/asana_oas.yaml).
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { UserCompact } from './user-compact';

/**
 * 
 * @export
 * @interface TimeTrackingEntryCompactAllOf
 */
export interface TimeTrackingEntryCompactAllOf {
    /**
     * Time in minutes tracked by the entry.
     * @type {number}
     * @memberof TimeTrackingEntryCompactAllOf
     */
    'duration_minutes'?: number;
    /**
     * The day that this entry is logged on.
     * @type {string}
     * @memberof TimeTrackingEntryCompactAllOf
     */
    'entered_on'?: string;
    /**
     * 
     * @type {UserCompact}
     * @memberof TimeTrackingEntryCompactAllOf
     */
    'created_by'?: UserCompact;
}

