/* tslint:disable */
/* eslint-disable */
/**
 * Asana
 * This is the interface for interacting with the [Asana Platform](https://developers.asana.com). Our API reference is generated from our [OpenAPI spec] (https://raw.githubusercontent.com/Asana/openapi/master/defs/asana_oas.yaml).
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * A *time tracking category* is a label that can be assigned to time tracking entries. Categories are workspace-scoped and allow users to classify logged time (e.g., \'Development\', \'Meetings\').
 * @export
 * @interface TimeTrackingCategoryCompact
 */
export interface TimeTrackingCategoryCompact {
    /**
     * Globally unique identifier of the resource, as a string.
     * @type {string}
     * @memberof TimeTrackingCategoryCompact
     */
    'gid'?: string;
    /**
     * The base type of this resource.
     * @type {string}
     * @memberof TimeTrackingCategoryCompact
     */
    'resource_type'?: string;
    /**
     * The name of the time tracking category.
     * @type {string}
     * @memberof TimeTrackingCategoryCompact
     */
    'name'?: string;
    /**
     * The color associated with this category for display purposes.
     * @type {string}
     * @memberof TimeTrackingCategoryCompact
     */
    'color'?: TimeTrackingCategoryCompactColorEnum;
}

/**
    * @export
    * @enum {string}
    */
export enum TimeTrackingCategoryCompactColorEnum {
    None = 'none',
    Red = 'red',
    Orange = 'orange',
    YellowOrange = 'yellow-orange',
    Yellow = 'yellow',
    YellowGreen = 'yellow-green',
    Green = 'green',
    BlueGreen = 'blue-green',
    Aqua = 'aqua',
    Blue = 'blue',
    Indigo = 'indigo',
    Purple = 'purple',
    Magenta = 'magenta',
    HotPink = 'hot-pink',
    Pink = 'pink',
    CoolGray = 'cool-gray'
}


