/* tslint:disable */
/* eslint-disable */
/**
 * Asana
 * This is the interface for interacting with the [Asana Platform](https://developers.asana.com). Our API reference is generated from our [OpenAPI spec] (https://raw.githubusercontent.com/Asana/openapi/master/defs/asana_oas.yaml).
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * A map of the user\'s profile photo in various sizes, or null if no photo is set. Sizes provided are 21, 27, 36, 60, 128, and 1024. All images are in PNG format, except for 1024 (which is in JPEG format).
 * @export
 * @interface UserBaseResponseAllOfPhoto
 */
export interface UserBaseResponseAllOfPhoto {
    /**
     * PNG image of the user at 21x21 pixels.
     * @type {string}
     * @memberof UserBaseResponseAllOfPhoto
     */
    'image_21x21'?: string;
    /**
     * PNG image of the user at 27x27 pixels.
     * @type {string}
     * @memberof UserBaseResponseAllOfPhoto
     */
    'image_27x27'?: string;
    /**
     * PNG image of the user at 36x36 pixels.
     * @type {string}
     * @memberof UserBaseResponseAllOfPhoto
     */
    'image_36x36'?: string;
    /**
     * PNG image of the user at 60x60 pixels.
     * @type {string}
     * @memberof UserBaseResponseAllOfPhoto
     */
    'image_60x60'?: string;
    /**
     * PNG image of the user at 128x128 pixels.
     * @type {string}
     * @memberof UserBaseResponseAllOfPhoto
     */
    'image_128x128'?: string;
    /**
     * JPEG image of the user at 1024x1024 pixels.
     * @type {string}
     * @memberof UserBaseResponseAllOfPhoto
     */
    'image_1024x1024'?: string;
}

