/* tslint:disable */
/* eslint-disable */
/**
 * Asana
 * This is the interface for interacting with the [Asana Platform](https://developers.asana.com). Our API reference is generated from our [OpenAPI spec] (https://raw.githubusercontent.com/Asana/developer-docs/master/defs/asana_oas.yaml).
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { UserCompact } from './user-compact';
import { UserResponseAllOf } from './user-response-all-of';
import { UserResponseAllOfPhoto } from './user-response-all-of-photo';
import { WorkspaceCompact } from './workspace-compact';

/**
 * @type UserResponse
 * @export
 */
export type UserResponse = UserCompact & UserResponseAllOf;


