/* tslint:disable */
/* eslint-disable */
/**
 * Asana
 * This is the interface for interacting with the [Asana Platform](https://developers.asana.com). Our API reference is generated from our [OpenAPI spec] (https://raw.githubusercontent.com/Asana/developer-docs/master/defs/asana_oas.yaml).
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * A map of the user’s profile photo in various sizes, or null if no photo is set. Sizes provided are 21, 27, 36, 60, 128, and 1024. All images are in PNG format, except for 1024 (which is in JPEG format).
 * @export
 * @interface UserResponseAllOfPhoto
 */
export interface UserResponseAllOfPhoto {
    /**
     * 
     * @type {string}
     * @memberof UserResponseAllOfPhoto
     */
    'image_21x21'?: string;
    /**
     * 
     * @type {string}
     * @memberof UserResponseAllOfPhoto
     */
    'image_27x27'?: string;
    /**
     * 
     * @type {string}
     * @memberof UserResponseAllOfPhoto
     */
    'image_36x36'?: string;
    /**
     * 
     * @type {string}
     * @memberof UserResponseAllOfPhoto
     */
    'image_60x60'?: string;
    /**
     * 
     * @type {string}
     * @memberof UserResponseAllOfPhoto
     */
    'image_128x128'?: string;
    /**
     * 
     * @type {string}
     * @memberof UserResponseAllOfPhoto
     */
    'image_1024x1024'?: string;
}

