/* tslint:disable */
/* eslint-disable */
/**
 * Asana
 * This is the interface for interacting with the [Asana Platform](https://developers.asana.com). Our API reference is generated from our [OpenAPI spec] (https://raw.githubusercontent.com/Asana/openapi/master/defs/asana_oas.yaml).
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import globalAxios, { AxiosPromise, AxiosInstance, AxiosRequestConfig } from 'axios';
import { Configuration } from '../configuration';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from '../base';
// @ts-ignore
import { ErrorResponse } from '../types';
// @ts-ignore
import { InlineObject67 } from '../types';
// @ts-ignore
import { InlineObject68 } from '../types';
// @ts-ignore
import { InlineObject69 } from '../types';
// @ts-ignore
import { InlineObject70 } from '../types';
// @ts-ignore
import { InlineResponse2001 } from '../types';
// @ts-ignore
import { InlineResponse20041 } from '../types';
// @ts-ignore
import { InlineResponse20043 } from '../types';
// @ts-ignore
import { InlineResponse2018 } from '../types';
/**
 * TeamsApi - axios parameter creator
 * @export
 */
export const TeamsApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * The user making this call must be a member of the team in order to add others. The user being added must exist in the same organization as the team.  Returns the complete team membership record for the newly added user.
         * @summary Add a user to a team
         * @param {string} teamGid Globally unique identifier for the team.
         * @param {InlineObject69} inlineObject69 
         * @param {boolean} [optPretty] Provides “pretty” output. Provides the response in a “pretty” format. In the case of JSON this means doing proper line breaking and indentation to make it readable. This will take extra time and increase the response size so it is advisable only to use this during debugging.
         * @param {Array<'is_admin' | 'is_guest' | 'is_limited_access' | 'team' | 'team.name' | 'user' | 'user.name'>} [optFields] This endpoint returns a compact resource, which excludes some properties by default. To include those optional properties, set this query parameter to a comma-separated list of the properties you wish to include.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        addUserForTeam: async (teamGid: string, inlineObject69: InlineObject69, optPretty?: boolean, optFields?: Array<'is_admin' | 'is_guest' | 'is_limited_access' | 'team' | 'team.name' | 'user' | 'user.name'>, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'teamGid' is not null or undefined
            assertParamExists('addUserForTeam', 'teamGid', teamGid)
            // verify required parameter 'inlineObject69' is not null or undefined
            assertParamExists('addUserForTeam', 'inlineObject69', inlineObject69)
            const localVarPath = `/teams/{team_gid}/addUser`
                .replace(`{${"team_gid"}}`, encodeURIComponent(String(teamGid)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication oauth2 required
            // oauth required
            await setOAuthToObject(localVarHeaderParameter, "oauth2", [], configuration)

            // authentication personalAccessToken required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            if (optPretty !== undefined) {
                localVarQueryParameter['opt_pretty'] = optPretty;
            }

            if (optFields) {
                localVarQueryParameter['opt_fields'] = optFields.join(COLLECTION_FORMATS.csv);
            }


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(inlineObject69, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Creates a team within the current workspace.
         * @summary Create a team
         * @param {InlineObject67} inlineObject67 
         * @param {boolean} [optPretty] Provides “pretty” output. Provides the response in a “pretty” format. In the case of JSON this means doing proper line breaking and indentation to make it readable. This will take extra time and increase the response size so it is advisable only to use this during debugging.
         * @param {Array<'description' | 'edit_team_name_or_description_access_level' | 'edit_team_visibility_or_trash_team_access_level' | 'guest_invite_management_access_level' | 'html_description' | 'join_request_management_access_level' | 'member_invite_management_access_level' | 'name' | 'organization' | 'organization.name' | 'permalink_url' | 'team_member_removal_access_level' | 'visibility'>} [optFields] This endpoint returns a compact resource, which excludes some properties by default. To include those optional properties, set this query parameter to a comma-separated list of the properties you wish to include.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createTeam: async (inlineObject67: InlineObject67, optPretty?: boolean, optFields?: Array<'description' | 'edit_team_name_or_description_access_level' | 'edit_team_visibility_or_trash_team_access_level' | 'guest_invite_management_access_level' | 'html_description' | 'join_request_management_access_level' | 'member_invite_management_access_level' | 'name' | 'organization' | 'organization.name' | 'permalink_url' | 'team_member_removal_access_level' | 'visibility'>, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'inlineObject67' is not null or undefined
            assertParamExists('createTeam', 'inlineObject67', inlineObject67)
            const localVarPath = `/teams`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication oauth2 required
            // oauth required
            await setOAuthToObject(localVarHeaderParameter, "oauth2", [], configuration)

            // authentication personalAccessToken required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            if (optPretty !== undefined) {
                localVarQueryParameter['opt_pretty'] = optPretty;
            }

            if (optFields) {
                localVarQueryParameter['opt_fields'] = optFields.join(COLLECTION_FORMATS.csv);
            }


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(inlineObject67, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Returns the full record for a single team.
         * @summary Get a team
         * @param {string} teamGid Globally unique identifier for the team.
         * @param {boolean} [optPretty] Provides “pretty” output. Provides the response in a “pretty” format. In the case of JSON this means doing proper line breaking and indentation to make it readable. This will take extra time and increase the response size so it is advisable only to use this during debugging.
         * @param {Array<'description' | 'edit_team_name_or_description_access_level' | 'edit_team_visibility_or_trash_team_access_level' | 'guest_invite_management_access_level' | 'html_description' | 'join_request_management_access_level' | 'member_invite_management_access_level' | 'name' | 'organization' | 'organization.name' | 'permalink_url' | 'team_member_removal_access_level' | 'visibility'>} [optFields] This endpoint returns a compact resource, which excludes some properties by default. To include those optional properties, set this query parameter to a comma-separated list of the properties you wish to include.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getTeam: async (teamGid: string, optPretty?: boolean, optFields?: Array<'description' | 'edit_team_name_or_description_access_level' | 'edit_team_visibility_or_trash_team_access_level' | 'guest_invite_management_access_level' | 'html_description' | 'join_request_management_access_level' | 'member_invite_management_access_level' | 'name' | 'organization' | 'organization.name' | 'permalink_url' | 'team_member_removal_access_level' | 'visibility'>, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'teamGid' is not null or undefined
            assertParamExists('getTeam', 'teamGid', teamGid)
            const localVarPath = `/teams/{team_gid}`
                .replace(`{${"team_gid"}}`, encodeURIComponent(String(teamGid)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication oauth2 required
            // oauth required
            await setOAuthToObject(localVarHeaderParameter, "oauth2", [], configuration)

            // authentication personalAccessToken required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            if (optPretty !== undefined) {
                localVarQueryParameter['opt_pretty'] = optPretty;
            }

            if (optFields) {
                localVarQueryParameter['opt_fields'] = optFields.join(COLLECTION_FORMATS.csv);
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Returns the compact records for all teams to which the given user is assigned.
         * @summary Get teams for a user
         * @param {string} userGid A string identifying a user. This can either be the string \&quot;me\&quot;, an email, or the gid of a user.
         * @param {string} organization The workspace or organization to filter teams on.
         * @param {boolean} [optPretty] Provides “pretty” output. Provides the response in a “pretty” format. In the case of JSON this means doing proper line breaking and indentation to make it readable. This will take extra time and increase the response size so it is advisable only to use this during debugging.
         * @param {number} [limit] Results per page. The number of objects to return per page. The value must be between 1 and 100.
         * @param {string} [offset] Offset token. An offset to the next page returned by the API. A pagination request will return an offset token, which can be used as an input parameter to the next request. If an offset is not passed in, the API will return the first page of results. \&#39;Note: You can only pass in an offset that was returned to you via a previously paginated request.\&#39;
         * @param {Array<'description' | 'edit_team_name_or_description_access_level' | 'edit_team_visibility_or_trash_team_access_level' | 'guest_invite_management_access_level' | 'html_description' | 'join_request_management_access_level' | 'member_invite_management_access_level' | 'name' | 'offset' | 'organization' | 'organization.name' | 'path' | 'permalink_url' | 'team_member_removal_access_level' | 'uri' | 'visibility'>} [optFields] This endpoint returns a compact resource, which excludes some properties by default. To include those optional properties, set this query parameter to a comma-separated list of the properties you wish to include.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getTeamsForUser: async (userGid: string, organization: string, optPretty?: boolean, limit?: number, offset?: string, optFields?: Array<'description' | 'edit_team_name_or_description_access_level' | 'edit_team_visibility_or_trash_team_access_level' | 'guest_invite_management_access_level' | 'html_description' | 'join_request_management_access_level' | 'member_invite_management_access_level' | 'name' | 'offset' | 'organization' | 'organization.name' | 'path' | 'permalink_url' | 'team_member_removal_access_level' | 'uri' | 'visibility'>, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'userGid' is not null or undefined
            assertParamExists('getTeamsForUser', 'userGid', userGid)
            // verify required parameter 'organization' is not null or undefined
            assertParamExists('getTeamsForUser', 'organization', organization)
            const localVarPath = `/users/{user_gid}/teams`
                .replace(`{${"user_gid"}}`, encodeURIComponent(String(userGid)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication oauth2 required
            // oauth required
            await setOAuthToObject(localVarHeaderParameter, "oauth2", [], configuration)

            // authentication personalAccessToken required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            if (optPretty !== undefined) {
                localVarQueryParameter['opt_pretty'] = optPretty;
            }

            if (limit !== undefined) {
                localVarQueryParameter['limit'] = limit;
            }

            if (offset !== undefined) {
                localVarQueryParameter['offset'] = offset;
            }

            if (organization !== undefined) {
                localVarQueryParameter['organization'] = organization;
            }

            if (optFields) {
                localVarQueryParameter['opt_fields'] = optFields.join(COLLECTION_FORMATS.csv);
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Returns the compact records for all teams in the workspace visible to the authorized user.
         * @summary Get teams in a workspace
         * @param {string} workspaceGid Globally unique identifier for the workspace or organization.
         * @param {boolean} [optPretty] Provides “pretty” output. Provides the response in a “pretty” format. In the case of JSON this means doing proper line breaking and indentation to make it readable. This will take extra time and increase the response size so it is advisable only to use this during debugging.
         * @param {number} [limit] Results per page. The number of objects to return per page. The value must be between 1 and 100.
         * @param {string} [offset] Offset token. An offset to the next page returned by the API. A pagination request will return an offset token, which can be used as an input parameter to the next request. If an offset is not passed in, the API will return the first page of results. \&#39;Note: You can only pass in an offset that was returned to you via a previously paginated request.\&#39;
         * @param {Array<'description' | 'edit_team_name_or_description_access_level' | 'edit_team_visibility_or_trash_team_access_level' | 'guest_invite_management_access_level' | 'html_description' | 'join_request_management_access_level' | 'member_invite_management_access_level' | 'name' | 'offset' | 'organization' | 'organization.name' | 'path' | 'permalink_url' | 'team_member_removal_access_level' | 'uri' | 'visibility'>} [optFields] This endpoint returns a compact resource, which excludes some properties by default. To include those optional properties, set this query parameter to a comma-separated list of the properties you wish to include.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getTeamsForWorkspace: async (workspaceGid: string, optPretty?: boolean, limit?: number, offset?: string, optFields?: Array<'description' | 'edit_team_name_or_description_access_level' | 'edit_team_visibility_or_trash_team_access_level' | 'guest_invite_management_access_level' | 'html_description' | 'join_request_management_access_level' | 'member_invite_management_access_level' | 'name' | 'offset' | 'organization' | 'organization.name' | 'path' | 'permalink_url' | 'team_member_removal_access_level' | 'uri' | 'visibility'>, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'workspaceGid' is not null or undefined
            assertParamExists('getTeamsForWorkspace', 'workspaceGid', workspaceGid)
            const localVarPath = `/workspaces/{workspace_gid}/teams`
                .replace(`{${"workspace_gid"}}`, encodeURIComponent(String(workspaceGid)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication oauth2 required
            // oauth required
            await setOAuthToObject(localVarHeaderParameter, "oauth2", [], configuration)

            // authentication personalAccessToken required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            if (optPretty !== undefined) {
                localVarQueryParameter['opt_pretty'] = optPretty;
            }

            if (limit !== undefined) {
                localVarQueryParameter['limit'] = limit;
            }

            if (offset !== undefined) {
                localVarQueryParameter['offset'] = offset;
            }

            if (optFields) {
                localVarQueryParameter['opt_fields'] = optFields.join(COLLECTION_FORMATS.csv);
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * The user making this call must be a member of the team in order to remove themselves or others.
         * @summary Remove a user from a team
         * @param {string} teamGid Globally unique identifier for the team.
         * @param {InlineObject70} inlineObject70 
         * @param {boolean} [optPretty] Provides “pretty” output. Provides the response in a “pretty” format. In the case of JSON this means doing proper line breaking and indentation to make it readable. This will take extra time and increase the response size so it is advisable only to use this during debugging.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        removeUserForTeam: async (teamGid: string, inlineObject70: InlineObject70, optPretty?: boolean, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'teamGid' is not null or undefined
            assertParamExists('removeUserForTeam', 'teamGid', teamGid)
            // verify required parameter 'inlineObject70' is not null or undefined
            assertParamExists('removeUserForTeam', 'inlineObject70', inlineObject70)
            const localVarPath = `/teams/{team_gid}/removeUser`
                .replace(`{${"team_gid"}}`, encodeURIComponent(String(teamGid)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication oauth2 required
            // oauth required
            await setOAuthToObject(localVarHeaderParameter, "oauth2", [], configuration)

            // authentication personalAccessToken required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            if (optPretty !== undefined) {
                localVarQueryParameter['opt_pretty'] = optPretty;
            }


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(inlineObject70, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Updates a team within the current workspace.
         * @summary Update a team
         * @param {string} teamGid Globally unique identifier for the team.
         * @param {InlineObject68} inlineObject68 
         * @param {boolean} [optPretty] Provides “pretty” output. Provides the response in a “pretty” format. In the case of JSON this means doing proper line breaking and indentation to make it readable. This will take extra time and increase the response size so it is advisable only to use this during debugging.
         * @param {Array<'description' | 'edit_team_name_or_description_access_level' | 'edit_team_visibility_or_trash_team_access_level' | 'guest_invite_management_access_level' | 'html_description' | 'join_request_management_access_level' | 'member_invite_management_access_level' | 'name' | 'organization' | 'organization.name' | 'permalink_url' | 'team_member_removal_access_level' | 'visibility'>} [optFields] This endpoint returns a compact resource, which excludes some properties by default. To include those optional properties, set this query parameter to a comma-separated list of the properties you wish to include.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateTeam: async (teamGid: string, inlineObject68: InlineObject68, optPretty?: boolean, optFields?: Array<'description' | 'edit_team_name_or_description_access_level' | 'edit_team_visibility_or_trash_team_access_level' | 'guest_invite_management_access_level' | 'html_description' | 'join_request_management_access_level' | 'member_invite_management_access_level' | 'name' | 'organization' | 'organization.name' | 'permalink_url' | 'team_member_removal_access_level' | 'visibility'>, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'teamGid' is not null or undefined
            assertParamExists('updateTeam', 'teamGid', teamGid)
            // verify required parameter 'inlineObject68' is not null or undefined
            assertParamExists('updateTeam', 'inlineObject68', inlineObject68)
            const localVarPath = `/teams/{team_gid}`
                .replace(`{${"team_gid"}}`, encodeURIComponent(String(teamGid)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PUT', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication oauth2 required
            // oauth required
            await setOAuthToObject(localVarHeaderParameter, "oauth2", [], configuration)

            // authentication personalAccessToken required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            if (optPretty !== undefined) {
                localVarQueryParameter['opt_pretty'] = optPretty;
            }

            if (optFields) {
                localVarQueryParameter['opt_fields'] = optFields.join(COLLECTION_FORMATS.csv);
            }


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(inlineObject68, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * TeamsApi - functional programming interface
 * @export
 */
export const TeamsApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = TeamsApiAxiosParamCreator(configuration)
    return {
        /**
         * The user making this call must be a member of the team in order to add others. The user being added must exist in the same organization as the team.  Returns the complete team membership record for the newly added user.
         * @summary Add a user to a team
         * @param {string} teamGid Globally unique identifier for the team.
         * @param {InlineObject69} inlineObject69 
         * @param {boolean} [optPretty] Provides “pretty” output. Provides the response in a “pretty” format. In the case of JSON this means doing proper line breaking and indentation to make it readable. This will take extra time and increase the response size so it is advisable only to use this during debugging.
         * @param {Array<'is_admin' | 'is_guest' | 'is_limited_access' | 'team' | 'team.name' | 'user' | 'user.name'>} [optFields] This endpoint returns a compact resource, which excludes some properties by default. To include those optional properties, set this query parameter to a comma-separated list of the properties you wish to include.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async addUserForTeam(teamGid: string, inlineObject69: InlineObject69, optPretty?: boolean, optFields?: Array<'is_admin' | 'is_guest' | 'is_limited_access' | 'team' | 'team.name' | 'user' | 'user.name'>, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<InlineResponse20041>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.addUserForTeam(teamGid, inlineObject69, optPretty, optFields, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * Creates a team within the current workspace.
         * @summary Create a team
         * @param {InlineObject67} inlineObject67 
         * @param {boolean} [optPretty] Provides “pretty” output. Provides the response in a “pretty” format. In the case of JSON this means doing proper line breaking and indentation to make it readable. This will take extra time and increase the response size so it is advisable only to use this during debugging.
         * @param {Array<'description' | 'edit_team_name_or_description_access_level' | 'edit_team_visibility_or_trash_team_access_level' | 'guest_invite_management_access_level' | 'html_description' | 'join_request_management_access_level' | 'member_invite_management_access_level' | 'name' | 'organization' | 'organization.name' | 'permalink_url' | 'team_member_removal_access_level' | 'visibility'>} [optFields] This endpoint returns a compact resource, which excludes some properties by default. To include those optional properties, set this query parameter to a comma-separated list of the properties you wish to include.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async createTeam(inlineObject67: InlineObject67, optPretty?: boolean, optFields?: Array<'description' | 'edit_team_name_or_description_access_level' | 'edit_team_visibility_or_trash_team_access_level' | 'guest_invite_management_access_level' | 'html_description' | 'join_request_management_access_level' | 'member_invite_management_access_level' | 'name' | 'organization' | 'organization.name' | 'permalink_url' | 'team_member_removal_access_level' | 'visibility'>, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<InlineResponse2018>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.createTeam(inlineObject67, optPretty, optFields, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * Returns the full record for a single team.
         * @summary Get a team
         * @param {string} teamGid Globally unique identifier for the team.
         * @param {boolean} [optPretty] Provides “pretty” output. Provides the response in a “pretty” format. In the case of JSON this means doing proper line breaking and indentation to make it readable. This will take extra time and increase the response size so it is advisable only to use this during debugging.
         * @param {Array<'description' | 'edit_team_name_or_description_access_level' | 'edit_team_visibility_or_trash_team_access_level' | 'guest_invite_management_access_level' | 'html_description' | 'join_request_management_access_level' | 'member_invite_management_access_level' | 'name' | 'organization' | 'organization.name' | 'permalink_url' | 'team_member_removal_access_level' | 'visibility'>} [optFields] This endpoint returns a compact resource, which excludes some properties by default. To include those optional properties, set this query parameter to a comma-separated list of the properties you wish to include.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getTeam(teamGid: string, optPretty?: boolean, optFields?: Array<'description' | 'edit_team_name_or_description_access_level' | 'edit_team_visibility_or_trash_team_access_level' | 'guest_invite_management_access_level' | 'html_description' | 'join_request_management_access_level' | 'member_invite_management_access_level' | 'name' | 'organization' | 'organization.name' | 'permalink_url' | 'team_member_removal_access_level' | 'visibility'>, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<InlineResponse2018>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getTeam(teamGid, optPretty, optFields, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * Returns the compact records for all teams to which the given user is assigned.
         * @summary Get teams for a user
         * @param {string} userGid A string identifying a user. This can either be the string \&quot;me\&quot;, an email, or the gid of a user.
         * @param {string} organization The workspace or organization to filter teams on.
         * @param {boolean} [optPretty] Provides “pretty” output. Provides the response in a “pretty” format. In the case of JSON this means doing proper line breaking and indentation to make it readable. This will take extra time and increase the response size so it is advisable only to use this during debugging.
         * @param {number} [limit] Results per page. The number of objects to return per page. The value must be between 1 and 100.
         * @param {string} [offset] Offset token. An offset to the next page returned by the API. A pagination request will return an offset token, which can be used as an input parameter to the next request. If an offset is not passed in, the API will return the first page of results. \&#39;Note: You can only pass in an offset that was returned to you via a previously paginated request.\&#39;
         * @param {Array<'description' | 'edit_team_name_or_description_access_level' | 'edit_team_visibility_or_trash_team_access_level' | 'guest_invite_management_access_level' | 'html_description' | 'join_request_management_access_level' | 'member_invite_management_access_level' | 'name' | 'offset' | 'organization' | 'organization.name' | 'path' | 'permalink_url' | 'team_member_removal_access_level' | 'uri' | 'visibility'>} [optFields] This endpoint returns a compact resource, which excludes some properties by default. To include those optional properties, set this query parameter to a comma-separated list of the properties you wish to include.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getTeamsForUser(userGid: string, organization: string, optPretty?: boolean, limit?: number, offset?: string, optFields?: Array<'description' | 'edit_team_name_or_description_access_level' | 'edit_team_visibility_or_trash_team_access_level' | 'guest_invite_management_access_level' | 'html_description' | 'join_request_management_access_level' | 'member_invite_management_access_level' | 'name' | 'offset' | 'organization' | 'organization.name' | 'path' | 'permalink_url' | 'team_member_removal_access_level' | 'uri' | 'visibility'>, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<InlineResponse20043>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getTeamsForUser(userGid, organization, optPretty, limit, offset, optFields, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * Returns the compact records for all teams in the workspace visible to the authorized user.
         * @summary Get teams in a workspace
         * @param {string} workspaceGid Globally unique identifier for the workspace or organization.
         * @param {boolean} [optPretty] Provides “pretty” output. Provides the response in a “pretty” format. In the case of JSON this means doing proper line breaking and indentation to make it readable. This will take extra time and increase the response size so it is advisable only to use this during debugging.
         * @param {number} [limit] Results per page. The number of objects to return per page. The value must be between 1 and 100.
         * @param {string} [offset] Offset token. An offset to the next page returned by the API. A pagination request will return an offset token, which can be used as an input parameter to the next request. If an offset is not passed in, the API will return the first page of results. \&#39;Note: You can only pass in an offset that was returned to you via a previously paginated request.\&#39;
         * @param {Array<'description' | 'edit_team_name_or_description_access_level' | 'edit_team_visibility_or_trash_team_access_level' | 'guest_invite_management_access_level' | 'html_description' | 'join_request_management_access_level' | 'member_invite_management_access_level' | 'name' | 'offset' | 'organization' | 'organization.name' | 'path' | 'permalink_url' | 'team_member_removal_access_level' | 'uri' | 'visibility'>} [optFields] This endpoint returns a compact resource, which excludes some properties by default. To include those optional properties, set this query parameter to a comma-separated list of the properties you wish to include.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getTeamsForWorkspace(workspaceGid: string, optPretty?: boolean, limit?: number, offset?: string, optFields?: Array<'description' | 'edit_team_name_or_description_access_level' | 'edit_team_visibility_or_trash_team_access_level' | 'guest_invite_management_access_level' | 'html_description' | 'join_request_management_access_level' | 'member_invite_management_access_level' | 'name' | 'offset' | 'organization' | 'organization.name' | 'path' | 'permalink_url' | 'team_member_removal_access_level' | 'uri' | 'visibility'>, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<InlineResponse20043>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getTeamsForWorkspace(workspaceGid, optPretty, limit, offset, optFields, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * The user making this call must be a member of the team in order to remove themselves or others.
         * @summary Remove a user from a team
         * @param {string} teamGid Globally unique identifier for the team.
         * @param {InlineObject70} inlineObject70 
         * @param {boolean} [optPretty] Provides “pretty” output. Provides the response in a “pretty” format. In the case of JSON this means doing proper line breaking and indentation to make it readable. This will take extra time and increase the response size so it is advisable only to use this during debugging.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async removeUserForTeam(teamGid: string, inlineObject70: InlineObject70, optPretty?: boolean, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<InlineResponse2001>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.removeUserForTeam(teamGid, inlineObject70, optPretty, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * Updates a team within the current workspace.
         * @summary Update a team
         * @param {string} teamGid Globally unique identifier for the team.
         * @param {InlineObject68} inlineObject68 
         * @param {boolean} [optPretty] Provides “pretty” output. Provides the response in a “pretty” format. In the case of JSON this means doing proper line breaking and indentation to make it readable. This will take extra time and increase the response size so it is advisable only to use this during debugging.
         * @param {Array<'description' | 'edit_team_name_or_description_access_level' | 'edit_team_visibility_or_trash_team_access_level' | 'guest_invite_management_access_level' | 'html_description' | 'join_request_management_access_level' | 'member_invite_management_access_level' | 'name' | 'organization' | 'organization.name' | 'permalink_url' | 'team_member_removal_access_level' | 'visibility'>} [optFields] This endpoint returns a compact resource, which excludes some properties by default. To include those optional properties, set this query parameter to a comma-separated list of the properties you wish to include.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async updateTeam(teamGid: string, inlineObject68: InlineObject68, optPretty?: boolean, optFields?: Array<'description' | 'edit_team_name_or_description_access_level' | 'edit_team_visibility_or_trash_team_access_level' | 'guest_invite_management_access_level' | 'html_description' | 'join_request_management_access_level' | 'member_invite_management_access_level' | 'name' | 'organization' | 'organization.name' | 'permalink_url' | 'team_member_removal_access_level' | 'visibility'>, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<InlineResponse2018>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.updateTeam(teamGid, inlineObject68, optPretty, optFields, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
    }
};

/**
 * TeamsApi - factory interface
 * @export
 */
export const TeamsApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = TeamsApiFp(configuration)
    return {
        /**
         * The user making this call must be a member of the team in order to add others. The user being added must exist in the same organization as the team.  Returns the complete team membership record for the newly added user.
         * @summary Add a user to a team
         * @param {string} teamGid Globally unique identifier for the team.
         * @param {InlineObject69} inlineObject69 
         * @param {boolean} [optPretty] Provides “pretty” output. Provides the response in a “pretty” format. In the case of JSON this means doing proper line breaking and indentation to make it readable. This will take extra time and increase the response size so it is advisable only to use this during debugging.
         * @param {Array<'is_admin' | 'is_guest' | 'is_limited_access' | 'team' | 'team.name' | 'user' | 'user.name'>} [optFields] This endpoint returns a compact resource, which excludes some properties by default. To include those optional properties, set this query parameter to a comma-separated list of the properties you wish to include.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        addUserForTeam(teamGid: string, inlineObject69: InlineObject69, optPretty?: boolean, optFields?: Array<'is_admin' | 'is_guest' | 'is_limited_access' | 'team' | 'team.name' | 'user' | 'user.name'>, options?: any): AxiosPromise<InlineResponse20041> {
            return localVarFp.addUserForTeam(teamGid, inlineObject69, optPretty, optFields, options).then((request) => request(axios, basePath));
        },
        /**
         * Creates a team within the current workspace.
         * @summary Create a team
         * @param {InlineObject67} inlineObject67 
         * @param {boolean} [optPretty] Provides “pretty” output. Provides the response in a “pretty” format. In the case of JSON this means doing proper line breaking and indentation to make it readable. This will take extra time and increase the response size so it is advisable only to use this during debugging.
         * @param {Array<'description' | 'edit_team_name_or_description_access_level' | 'edit_team_visibility_or_trash_team_access_level' | 'guest_invite_management_access_level' | 'html_description' | 'join_request_management_access_level' | 'member_invite_management_access_level' | 'name' | 'organization' | 'organization.name' | 'permalink_url' | 'team_member_removal_access_level' | 'visibility'>} [optFields] This endpoint returns a compact resource, which excludes some properties by default. To include those optional properties, set this query parameter to a comma-separated list of the properties you wish to include.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createTeam(inlineObject67: InlineObject67, optPretty?: boolean, optFields?: Array<'description' | 'edit_team_name_or_description_access_level' | 'edit_team_visibility_or_trash_team_access_level' | 'guest_invite_management_access_level' | 'html_description' | 'join_request_management_access_level' | 'member_invite_management_access_level' | 'name' | 'organization' | 'organization.name' | 'permalink_url' | 'team_member_removal_access_level' | 'visibility'>, options?: any): AxiosPromise<InlineResponse2018> {
            return localVarFp.createTeam(inlineObject67, optPretty, optFields, options).then((request) => request(axios, basePath));
        },
        /**
         * Returns the full record for a single team.
         * @summary Get a team
         * @param {string} teamGid Globally unique identifier for the team.
         * @param {boolean} [optPretty] Provides “pretty” output. Provides the response in a “pretty” format. In the case of JSON this means doing proper line breaking and indentation to make it readable. This will take extra time and increase the response size so it is advisable only to use this during debugging.
         * @param {Array<'description' | 'edit_team_name_or_description_access_level' | 'edit_team_visibility_or_trash_team_access_level' | 'guest_invite_management_access_level' | 'html_description' | 'join_request_management_access_level' | 'member_invite_management_access_level' | 'name' | 'organization' | 'organization.name' | 'permalink_url' | 'team_member_removal_access_level' | 'visibility'>} [optFields] This endpoint returns a compact resource, which excludes some properties by default. To include those optional properties, set this query parameter to a comma-separated list of the properties you wish to include.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getTeam(teamGid: string, optPretty?: boolean, optFields?: Array<'description' | 'edit_team_name_or_description_access_level' | 'edit_team_visibility_or_trash_team_access_level' | 'guest_invite_management_access_level' | 'html_description' | 'join_request_management_access_level' | 'member_invite_management_access_level' | 'name' | 'organization' | 'organization.name' | 'permalink_url' | 'team_member_removal_access_level' | 'visibility'>, options?: any): AxiosPromise<InlineResponse2018> {
            return localVarFp.getTeam(teamGid, optPretty, optFields, options).then((request) => request(axios, basePath));
        },
        /**
         * Returns the compact records for all teams to which the given user is assigned.
         * @summary Get teams for a user
         * @param {string} userGid A string identifying a user. This can either be the string \&quot;me\&quot;, an email, or the gid of a user.
         * @param {string} organization The workspace or organization to filter teams on.
         * @param {boolean} [optPretty] Provides “pretty” output. Provides the response in a “pretty” format. In the case of JSON this means doing proper line breaking and indentation to make it readable. This will take extra time and increase the response size so it is advisable only to use this during debugging.
         * @param {number} [limit] Results per page. The number of objects to return per page. The value must be between 1 and 100.
         * @param {string} [offset] Offset token. An offset to the next page returned by the API. A pagination request will return an offset token, which can be used as an input parameter to the next request. If an offset is not passed in, the API will return the first page of results. \&#39;Note: You can only pass in an offset that was returned to you via a previously paginated request.\&#39;
         * @param {Array<'description' | 'edit_team_name_or_description_access_level' | 'edit_team_visibility_or_trash_team_access_level' | 'guest_invite_management_access_level' | 'html_description' | 'join_request_management_access_level' | 'member_invite_management_access_level' | 'name' | 'offset' | 'organization' | 'organization.name' | 'path' | 'permalink_url' | 'team_member_removal_access_level' | 'uri' | 'visibility'>} [optFields] This endpoint returns a compact resource, which excludes some properties by default. To include those optional properties, set this query parameter to a comma-separated list of the properties you wish to include.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getTeamsForUser(userGid: string, organization: string, optPretty?: boolean, limit?: number, offset?: string, optFields?: Array<'description' | 'edit_team_name_or_description_access_level' | 'edit_team_visibility_or_trash_team_access_level' | 'guest_invite_management_access_level' | 'html_description' | 'join_request_management_access_level' | 'member_invite_management_access_level' | 'name' | 'offset' | 'organization' | 'organization.name' | 'path' | 'permalink_url' | 'team_member_removal_access_level' | 'uri' | 'visibility'>, options?: any): AxiosPromise<InlineResponse20043> {
            return localVarFp.getTeamsForUser(userGid, organization, optPretty, limit, offset, optFields, options).then((request) => request(axios, basePath));
        },
        /**
         * Returns the compact records for all teams in the workspace visible to the authorized user.
         * @summary Get teams in a workspace
         * @param {string} workspaceGid Globally unique identifier for the workspace or organization.
         * @param {boolean} [optPretty] Provides “pretty” output. Provides the response in a “pretty” format. In the case of JSON this means doing proper line breaking and indentation to make it readable. This will take extra time and increase the response size so it is advisable only to use this during debugging.
         * @param {number} [limit] Results per page. The number of objects to return per page. The value must be between 1 and 100.
         * @param {string} [offset] Offset token. An offset to the next page returned by the API. A pagination request will return an offset token, which can be used as an input parameter to the next request. If an offset is not passed in, the API will return the first page of results. \&#39;Note: You can only pass in an offset that was returned to you via a previously paginated request.\&#39;
         * @param {Array<'description' | 'edit_team_name_or_description_access_level' | 'edit_team_visibility_or_trash_team_access_level' | 'guest_invite_management_access_level' | 'html_description' | 'join_request_management_access_level' | 'member_invite_management_access_level' | 'name' | 'offset' | 'organization' | 'organization.name' | 'path' | 'permalink_url' | 'team_member_removal_access_level' | 'uri' | 'visibility'>} [optFields] This endpoint returns a compact resource, which excludes some properties by default. To include those optional properties, set this query parameter to a comma-separated list of the properties you wish to include.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getTeamsForWorkspace(workspaceGid: string, optPretty?: boolean, limit?: number, offset?: string, optFields?: Array<'description' | 'edit_team_name_or_description_access_level' | 'edit_team_visibility_or_trash_team_access_level' | 'guest_invite_management_access_level' | 'html_description' | 'join_request_management_access_level' | 'member_invite_management_access_level' | 'name' | 'offset' | 'organization' | 'organization.name' | 'path' | 'permalink_url' | 'team_member_removal_access_level' | 'uri' | 'visibility'>, options?: any): AxiosPromise<InlineResponse20043> {
            return localVarFp.getTeamsForWorkspace(workspaceGid, optPretty, limit, offset, optFields, options).then((request) => request(axios, basePath));
        },
        /**
         * The user making this call must be a member of the team in order to remove themselves or others.
         * @summary Remove a user from a team
         * @param {string} teamGid Globally unique identifier for the team.
         * @param {InlineObject70} inlineObject70 
         * @param {boolean} [optPretty] Provides “pretty” output. Provides the response in a “pretty” format. In the case of JSON this means doing proper line breaking and indentation to make it readable. This will take extra time and increase the response size so it is advisable only to use this during debugging.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        removeUserForTeam(teamGid: string, inlineObject70: InlineObject70, optPretty?: boolean, options?: any): AxiosPromise<InlineResponse2001> {
            return localVarFp.removeUserForTeam(teamGid, inlineObject70, optPretty, options).then((request) => request(axios, basePath));
        },
        /**
         * Updates a team within the current workspace.
         * @summary Update a team
         * @param {string} teamGid Globally unique identifier for the team.
         * @param {InlineObject68} inlineObject68 
         * @param {boolean} [optPretty] Provides “pretty” output. Provides the response in a “pretty” format. In the case of JSON this means doing proper line breaking and indentation to make it readable. This will take extra time and increase the response size so it is advisable only to use this during debugging.
         * @param {Array<'description' | 'edit_team_name_or_description_access_level' | 'edit_team_visibility_or_trash_team_access_level' | 'guest_invite_management_access_level' | 'html_description' | 'join_request_management_access_level' | 'member_invite_management_access_level' | 'name' | 'organization' | 'organization.name' | 'permalink_url' | 'team_member_removal_access_level' | 'visibility'>} [optFields] This endpoint returns a compact resource, which excludes some properties by default. To include those optional properties, set this query parameter to a comma-separated list of the properties you wish to include.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateTeam(teamGid: string, inlineObject68: InlineObject68, optPretty?: boolean, optFields?: Array<'description' | 'edit_team_name_or_description_access_level' | 'edit_team_visibility_or_trash_team_access_level' | 'guest_invite_management_access_level' | 'html_description' | 'join_request_management_access_level' | 'member_invite_management_access_level' | 'name' | 'organization' | 'organization.name' | 'permalink_url' | 'team_member_removal_access_level' | 'visibility'>, options?: any): AxiosPromise<InlineResponse2018> {
            return localVarFp.updateTeam(teamGid, inlineObject68, optPretty, optFields, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * TeamsApi - object-oriented interface
 * @export
 * @class TeamsApi
 * @extends {BaseAPI}
 */
export class TeamsApi extends BaseAPI {
    /**
     * The user making this call must be a member of the team in order to add others. The user being added must exist in the same organization as the team.  Returns the complete team membership record for the newly added user.
     * @summary Add a user to a team
     * @param {string} teamGid Globally unique identifier for the team.
     * @param {InlineObject69} inlineObject69 
     * @param {boolean} [optPretty] Provides “pretty” output. Provides the response in a “pretty” format. In the case of JSON this means doing proper line breaking and indentation to make it readable. This will take extra time and increase the response size so it is advisable only to use this during debugging.
     * @param {Array<'is_admin' | 'is_guest' | 'is_limited_access' | 'team' | 'team.name' | 'user' | 'user.name'>} [optFields] This endpoint returns a compact resource, which excludes some properties by default. To include those optional properties, set this query parameter to a comma-separated list of the properties you wish to include.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof TeamsApi
     */
    public addUserForTeam(teamGid: string, inlineObject69: InlineObject69, optPretty?: boolean, optFields?: Array<'is_admin' | 'is_guest' | 'is_limited_access' | 'team' | 'team.name' | 'user' | 'user.name'>, options?: AxiosRequestConfig) {
        return TeamsApiFp(this.configuration).addUserForTeam(teamGid, inlineObject69, optPretty, optFields, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Creates a team within the current workspace.
     * @summary Create a team
     * @param {InlineObject67} inlineObject67 
     * @param {boolean} [optPretty] Provides “pretty” output. Provides the response in a “pretty” format. In the case of JSON this means doing proper line breaking and indentation to make it readable. This will take extra time and increase the response size so it is advisable only to use this during debugging.
     * @param {Array<'description' | 'edit_team_name_or_description_access_level' | 'edit_team_visibility_or_trash_team_access_level' | 'guest_invite_management_access_level' | 'html_description' | 'join_request_management_access_level' | 'member_invite_management_access_level' | 'name' | 'organization' | 'organization.name' | 'permalink_url' | 'team_member_removal_access_level' | 'visibility'>} [optFields] This endpoint returns a compact resource, which excludes some properties by default. To include those optional properties, set this query parameter to a comma-separated list of the properties you wish to include.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof TeamsApi
     */
    public createTeam(inlineObject67: InlineObject67, optPretty?: boolean, optFields?: Array<'description' | 'edit_team_name_or_description_access_level' | 'edit_team_visibility_or_trash_team_access_level' | 'guest_invite_management_access_level' | 'html_description' | 'join_request_management_access_level' | 'member_invite_management_access_level' | 'name' | 'organization' | 'organization.name' | 'permalink_url' | 'team_member_removal_access_level' | 'visibility'>, options?: AxiosRequestConfig) {
        return TeamsApiFp(this.configuration).createTeam(inlineObject67, optPretty, optFields, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Returns the full record for a single team.
     * @summary Get a team
     * @param {string} teamGid Globally unique identifier for the team.
     * @param {boolean} [optPretty] Provides “pretty” output. Provides the response in a “pretty” format. In the case of JSON this means doing proper line breaking and indentation to make it readable. This will take extra time and increase the response size so it is advisable only to use this during debugging.
     * @param {Array<'description' | 'edit_team_name_or_description_access_level' | 'edit_team_visibility_or_trash_team_access_level' | 'guest_invite_management_access_level' | 'html_description' | 'join_request_management_access_level' | 'member_invite_management_access_level' | 'name' | 'organization' | 'organization.name' | 'permalink_url' | 'team_member_removal_access_level' | 'visibility'>} [optFields] This endpoint returns a compact resource, which excludes some properties by default. To include those optional properties, set this query parameter to a comma-separated list of the properties you wish to include.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof TeamsApi
     */
    public getTeam(teamGid: string, optPretty?: boolean, optFields?: Array<'description' | 'edit_team_name_or_description_access_level' | 'edit_team_visibility_or_trash_team_access_level' | 'guest_invite_management_access_level' | 'html_description' | 'join_request_management_access_level' | 'member_invite_management_access_level' | 'name' | 'organization' | 'organization.name' | 'permalink_url' | 'team_member_removal_access_level' | 'visibility'>, options?: AxiosRequestConfig) {
        return TeamsApiFp(this.configuration).getTeam(teamGid, optPretty, optFields, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Returns the compact records for all teams to which the given user is assigned.
     * @summary Get teams for a user
     * @param {string} userGid A string identifying a user. This can either be the string \&quot;me\&quot;, an email, or the gid of a user.
     * @param {string} organization The workspace or organization to filter teams on.
     * @param {boolean} [optPretty] Provides “pretty” output. Provides the response in a “pretty” format. In the case of JSON this means doing proper line breaking and indentation to make it readable. This will take extra time and increase the response size so it is advisable only to use this during debugging.
     * @param {number} [limit] Results per page. The number of objects to return per page. The value must be between 1 and 100.
     * @param {string} [offset] Offset token. An offset to the next page returned by the API. A pagination request will return an offset token, which can be used as an input parameter to the next request. If an offset is not passed in, the API will return the first page of results. \&#39;Note: You can only pass in an offset that was returned to you via a previously paginated request.\&#39;
     * @param {Array<'description' | 'edit_team_name_or_description_access_level' | 'edit_team_visibility_or_trash_team_access_level' | 'guest_invite_management_access_level' | 'html_description' | 'join_request_management_access_level' | 'member_invite_management_access_level' | 'name' | 'offset' | 'organization' | 'organization.name' | 'path' | 'permalink_url' | 'team_member_removal_access_level' | 'uri' | 'visibility'>} [optFields] This endpoint returns a compact resource, which excludes some properties by default. To include those optional properties, set this query parameter to a comma-separated list of the properties you wish to include.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof TeamsApi
     */
    public getTeamsForUser(userGid: string, organization: string, optPretty?: boolean, limit?: number, offset?: string, optFields?: Array<'description' | 'edit_team_name_or_description_access_level' | 'edit_team_visibility_or_trash_team_access_level' | 'guest_invite_management_access_level' | 'html_description' | 'join_request_management_access_level' | 'member_invite_management_access_level' | 'name' | 'offset' | 'organization' | 'organization.name' | 'path' | 'permalink_url' | 'team_member_removal_access_level' | 'uri' | 'visibility'>, options?: AxiosRequestConfig) {
        return TeamsApiFp(this.configuration).getTeamsForUser(userGid, organization, optPretty, limit, offset, optFields, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Returns the compact records for all teams in the workspace visible to the authorized user.
     * @summary Get teams in a workspace
     * @param {string} workspaceGid Globally unique identifier for the workspace or organization.
     * @param {boolean} [optPretty] Provides “pretty” output. Provides the response in a “pretty” format. In the case of JSON this means doing proper line breaking and indentation to make it readable. This will take extra time and increase the response size so it is advisable only to use this during debugging.
     * @param {number} [limit] Results per page. The number of objects to return per page. The value must be between 1 and 100.
     * @param {string} [offset] Offset token. An offset to the next page returned by the API. A pagination request will return an offset token, which can be used as an input parameter to the next request. If an offset is not passed in, the API will return the first page of results. \&#39;Note: You can only pass in an offset that was returned to you via a previously paginated request.\&#39;
     * @param {Array<'description' | 'edit_team_name_or_description_access_level' | 'edit_team_visibility_or_trash_team_access_level' | 'guest_invite_management_access_level' | 'html_description' | 'join_request_management_access_level' | 'member_invite_management_access_level' | 'name' | 'offset' | 'organization' | 'organization.name' | 'path' | 'permalink_url' | 'team_member_removal_access_level' | 'uri' | 'visibility'>} [optFields] This endpoint returns a compact resource, which excludes some properties by default. To include those optional properties, set this query parameter to a comma-separated list of the properties you wish to include.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof TeamsApi
     */
    public getTeamsForWorkspace(workspaceGid: string, optPretty?: boolean, limit?: number, offset?: string, optFields?: Array<'description' | 'edit_team_name_or_description_access_level' | 'edit_team_visibility_or_trash_team_access_level' | 'guest_invite_management_access_level' | 'html_description' | 'join_request_management_access_level' | 'member_invite_management_access_level' | 'name' | 'offset' | 'organization' | 'organization.name' | 'path' | 'permalink_url' | 'team_member_removal_access_level' | 'uri' | 'visibility'>, options?: AxiosRequestConfig) {
        return TeamsApiFp(this.configuration).getTeamsForWorkspace(workspaceGid, optPretty, limit, offset, optFields, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * The user making this call must be a member of the team in order to remove themselves or others.
     * @summary Remove a user from a team
     * @param {string} teamGid Globally unique identifier for the team.
     * @param {InlineObject70} inlineObject70 
     * @param {boolean} [optPretty] Provides “pretty” output. Provides the response in a “pretty” format. In the case of JSON this means doing proper line breaking and indentation to make it readable. This will take extra time and increase the response size so it is advisable only to use this during debugging.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof TeamsApi
     */
    public removeUserForTeam(teamGid: string, inlineObject70: InlineObject70, optPretty?: boolean, options?: AxiosRequestConfig) {
        return TeamsApiFp(this.configuration).removeUserForTeam(teamGid, inlineObject70, optPretty, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Updates a team within the current workspace.
     * @summary Update a team
     * @param {string} teamGid Globally unique identifier for the team.
     * @param {InlineObject68} inlineObject68 
     * @param {boolean} [optPretty] Provides “pretty” output. Provides the response in a “pretty” format. In the case of JSON this means doing proper line breaking and indentation to make it readable. This will take extra time and increase the response size so it is advisable only to use this during debugging.
     * @param {Array<'description' | 'edit_team_name_or_description_access_level' | 'edit_team_visibility_or_trash_team_access_level' | 'guest_invite_management_access_level' | 'html_description' | 'join_request_management_access_level' | 'member_invite_management_access_level' | 'name' | 'organization' | 'organization.name' | 'permalink_url' | 'team_member_removal_access_level' | 'visibility'>} [optFields] This endpoint returns a compact resource, which excludes some properties by default. To include those optional properties, set this query parameter to a comma-separated list of the properties you wish to include.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof TeamsApi
     */
    public updateTeam(teamGid: string, inlineObject68: InlineObject68, optPretty?: boolean, optFields?: Array<'description' | 'edit_team_name_or_description_access_level' | 'edit_team_visibility_or_trash_team_access_level' | 'guest_invite_management_access_level' | 'html_description' | 'join_request_management_access_level' | 'member_invite_management_access_level' | 'name' | 'organization' | 'organization.name' | 'permalink_url' | 'team_member_removal_access_level' | 'visibility'>, options?: AxiosRequestConfig) {
        return TeamsApiFp(this.configuration).updateTeam(teamGid, inlineObject68, optPretty, optFields, options).then((request) => request(this.axios, this.basePath));
    }
}
