name: Build
on:
  push:
    branches-ignore:
      - main

jobs:
  qa:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 20

      - name: Install Dependencies
        run: yarn

      - name: QA
        run: yarn qa
